"""Provides formatter-wide settings shown only from the General tree branch."""

from __future__ import annotations

from PyQt6.QtCore import pyqtSignal
from PyQt6.QtWidgets import QCheckBox, QVBoxLayout, QWidget

from opencae.ui.core.fields import FieldSpec, create_editor
from opencae.ui.templates import FieldStack, LabelRole, SectionHeading, label


DEFAULT_GLOBAL_SETTINGS = {
    "uppercase": True,
    "blank_lines": True,
    "prefix": "*",
    "separator": ", ",
    "float_format": ".6g",
    "comments": True,
    "comment_style": "** comment",
    "heading": True,
    "line_endings": "Platform default",
    "encoding": "UTF-8",
    "indentation": 0,
    "final_newline": True,
}


class DeckGlobalSettings(QWidget):
    """Edit persistent formatter-wide options using canonical OpenCAE controls."""

    changed = pyqtSignal()

    def __init__(self, parent=None):
        super().__init__(parent)
        self._editable = True
        self._section = "Formatting"
        self._state = dict(DEFAULT_GLOBAL_SETTINGS)
        self._editors: dict[str, QWidget] = {}

        self.root = QVBoxLayout(self)
        self.root.setContentsMargins(0, 0, 0, 0)
        self.root.setSpacing(12)
        self.title = SectionHeading("")
        self.root.addWidget(self.title)
        self.description = label("", role=LabelRole.MUTED)
        self.description.setWordWrap(True)
        self.root.addWidget(self.description)
        self.form = FieldStack()
        self.root.addWidget(self.form)
        self.root.addStretch(1)
        self.set_section(self._section)

    def set_section(self, section: str) -> None:
        """Show one setting family without discarding values from other pages."""
        self._capture()
        self._section = str(section)
        self.title.setText(self._section)
        self.form.clear()
        self._editors.clear()
        if self._section == "Comments":
            self._build_comments()
        elif self._section == "Output Style":
            self._build_output()
        else:
            self._build_formatting()
        self.set_editable(self._editable)

    def state(self) -> dict[str, object]:
        """Return the complete formatter-wide settings snapshot."""
        self._capture()
        return dict(self._state)

    def load_state(self, state: dict | None) -> None:
        """Load one profile's global settings and refresh the current family."""
        self._capture()
        self._state = dict(DEFAULT_GLOBAL_SETTINGS)
        if isinstance(state, dict):
            self._state.update(state)
        current = self._section
        self._section = ""
        self.set_section(current)

    def set_editable(self, editable: bool) -> None:
        """Enable profile inputs while keeping built-in format pages view-only."""
        self._editable = bool(editable)
        self.form.setEnabled(self._editable)
        for editor in self._editors.values():
            editor.setEnabled(self._editable)

    def _build_formatting(self) -> None:
        self.description.setText(
            "Defaults applied across records unless a record-specific setting overrides them."
        )
        self._add_bool("uppercase", "Uppercase generated keywords", True)
        self._add_bool("blank_lines", "Insert a blank line between top-level blocks", True)
        self._add(FieldSpec("prefix", "Keyword prefix", default="*"))
        self._add(
            FieldSpec(
                "separator",
                "Option separator",
                kind="choice",
                choices=(", ", ",", " "),
                default=", ",
            )
        )
        self._add(
            FieldSpec(
                "float_format",
                "Default float format",
                kind="choice",
                choices=(".6g", ".8g", ".12g", ".6f", ".12e"),
                default=".6g",
            )
        )

    def _build_comments(self) -> None:
        self.description.setText(
            "Controls comments generated by the formatter itself. Record templates remain focused on solver syntax."
        )
        self._add_bool("comments", "Emit generated comments", True)
        self._add(
            FieldSpec(
                "comment_style",
                "Comment style",
                kind="choice",
                choices=("** comment", "# comment", "/* comment */"),
                default="** comment",
            )
        )
        self._add_bool("heading", "Include OpenCAE generation heading", True)

    def _build_output(self) -> None:
        self.description.setText(
            "Controls file-wide text output rather than individual solver records."
        )
        self._add(
            FieldSpec(
                "line_endings",
                "Line endings",
                kind="choice",
                choices=("Platform default", "LF", "CRLF"),
                default="Platform default",
            )
        )
        self._add(
            FieldSpec(
                "encoding",
                "Encoding",
                kind="choice",
                choices=("UTF-8", "ASCII"),
                default="UTF-8",
            )
        )
        self._add(
            FieldSpec(
                "indentation",
                "Indentation spaces",
                kind="int",
                default=0,
                minimum=0,
                maximum=8,
            )
        )
        self._add_bool("final_newline", "End file with newline", True)

    def _add(self, spec: FieldSpec):
        editor = create_editor(spec)
        self._editors[spec.key] = editor
        _set_value(editor, self._state.get(spec.key, spec.default))
        _connect_changed(editor, self._editor_changed)
        self.form.addRow(spec.label, editor)
        return editor

    def _add_bool(self, key: str, text: str, default: bool) -> QCheckBox:
        editor = self._add(FieldSpec(key, text, kind="bool", default=default))
        if not isinstance(editor, QCheckBox):
            raise TypeError("Boolean deck setting must use QCheckBox")
        editor.setText(text)
        return editor

    def _editor_changed(self, *_args) -> None:
        self._capture()
        self.changed.emit()

    def _capture(self) -> None:
        for key, editor in self._editors.items():
            self._state[key] = _value(editor)


def _value(editor):
    if hasattr(editor, "isChecked"):
        return bool(editor.isChecked())
    if hasattr(editor, "currentText"):
        return str(editor.currentText())
    if hasattr(editor, "value"):
        return editor.value()
    if hasattr(editor, "text"):
        return str(editor.text())
    return None


def _set_value(editor, value) -> None:
    editor.blockSignals(True)
    try:
        if hasattr(editor, "setChecked"):
            editor.setChecked(bool(value))
        elif hasattr(editor, "setCurrentText"):
            editor.setCurrentText(str(value))
        elif hasattr(editor, "setValue"):
            editor.setValue(value)
        elif hasattr(editor, "setText"):
            editor.setText(str(value))
    finally:
        editor.blockSignals(False)


def _connect_changed(editor, callback) -> None:
    for name in ("toggled", "currentTextChanged", "valueChanged", "textChanged"):
        signal = getattr(editor, name, None)
        if signal is not None:
            signal.connect(callback)
            return
