"""Provides formatter-wide settings shown only from the General tree branch."""

from __future__ import annotations

from PyQt6.QtWidgets import QCheckBox, QVBoxLayout, QWidget

from opencae.ui.core.fields import FieldSpec, create_editor
from opencae.ui.templates import FieldStack, LabelRole, SectionHeading, label


class DeckGlobalSettings(QWidget):
    """Show global formatter options using canonical OpenCAE field templates."""

    def __init__(self, parent=None):
        """Create the reusable page container."""
        super().__init__(parent)
        self._editable = True
        self._editors: list[QWidget] = []
        self.root = QVBoxLayout(self)
        self.root.setContentsMargins(0, 0, 0, 0)
        self.root.setSpacing(12)
        self.title = SectionHeading("")
        self.root.addWidget(self.title)
        self.description = label("", role=LabelRole.MUTED)
        self.description.setWordWrap(True)
        self.root.addWidget(self.description)
        self.form = FieldStack()
        self.root.addWidget(self.form)
        self.root.addStretch(1)
        self.set_section("Formatting")

    def set_section(self, section: str) -> None:
        """Replace the fields with the requested global setting family."""
        self.title.setText(section)
        self.form.clear()
        self._editors.clear()
        if section == "Comments":
            self._build_comments()
        elif section == "Output Style":
            self._build_output()
        else:
            self._build_formatting()
        self.set_editable(self._editable)

    def set_editable(self, editable: bool) -> None:
        """Enable profile-editable controls while keeping explanatory text active."""
        self._editable = bool(editable)
        for editor in self._editors:
            editor.setEnabled(self._editable)

    def _build_formatting(self) -> None:
        """Build settings controlling generic keyword/data formatting."""
        self.description.setText(
            "Defaults applied across records unless a record-specific setting overrides them."
        )
        self._add_bool("uppercase", "Uppercase generated keywords", True)
        self._add_bool("blank_lines", "Insert a blank line between top-level blocks", True)
        self._add(FieldSpec("prefix", "Keyword prefix", default="*"))
        self._add(
            FieldSpec(
                "separator",
                "Option separator",
                kind="choice",
                choices=(", ", ",", " "),
                default=", ",
            )
        )
        self._add(
            FieldSpec(
                "float_format",
                "Default float format",
                kind="choice",
                choices=(".6g", ".8g", ".12g", ".6f", ".12e"),
                default=".6g",
            )
        )

    def _build_comments(self) -> None:
        """Build global comment syntax controls."""
        self.description.setText(
            "Controls comments generated by the formatter itself. Record templates remain focused on solver syntax."
        )
        self._add_bool("comments", "Emit generated comments", True)
        self._add(
            FieldSpec(
                "comment_style",
                "Comment style",
                kind="choice",
                choices=("** comment", "# comment", "/* comment */"),
                default="** comment",
            )
        )
        self._add_bool("heading", "Include OpenCAE generation heading", True)

    def _build_output(self) -> None:
        """Build file-level output presentation controls."""
        self.description.setText(
            "Controls file-wide text output rather than individual solver records."
        )
        self._add(
            FieldSpec(
                "line_endings",
                "Line endings",
                kind="choice",
                choices=("Platform default", "LF", "CRLF"),
                default="Platform default",
            )
        )
        self._add(
            FieldSpec(
                "encoding",
                "Encoding",
                kind="choice",
                choices=("UTF-8", "ASCII"),
                default="UTF-8",
            )
        )
        self._add(
            FieldSpec(
                "indentation",
                "Indentation spaces",
                kind="int",
                default=0,
                minimum=0,
                maximum=8,
            )
        )
        self._add_bool("final_newline", "End file with newline", True)

    def _add(self, spec: FieldSpec):
        """Create and add one canonical declarative field editor."""
        editor = create_editor(spec)
        self._editors.append(editor)
        self.form.addRow(spec.label, editor)
        return editor

    def _add_bool(self, key: str, text: str, default: bool) -> QCheckBox:
        """Add a canonical boolean editor with its caption on the checkbox itself."""
        editor = create_editor(FieldSpec(key, text, kind="bool", default=default))
        if not isinstance(editor, QCheckBox):
            raise TypeError("Boolean deck setting must use QCheckBox")
        editor.setText(text)
        self._editors.append(editor)
        self.form.addRow("", editor)
        return editor
