"""Provides formatter-wide settings shown only from the General tree branch."""

from __future__ import annotations

from PyQt6.QtWidgets import (
    QCheckBox,
    QComboBox,
    QFormLayout,
    QLabel,
    QLineEdit,
    QSpinBox,
    QVBoxLayout,
    QWidget,
)


class DeckGlobalSettings(QWidget):
    """Show global formatting options independently from record templates."""

    def __init__(self, parent=None):
        """Create the reusable page container."""
        super().__init__(parent)
        self.root = QVBoxLayout(self)
        self.root.setContentsMargins(0, 0, 0, 0)
        self.root.setSpacing(12)
        self.title = QLabel()
        self.title.setObjectName("SectionTitle")
        self.root.addWidget(self.title)
        self.description = QLabel()
        self.description.setWordWrap(True)
        self.root.addWidget(self.description)
        self.form = QFormLayout()
        self.form.setFieldGrowthPolicy(QFormLayout.FieldGrowthPolicy.AllNonFixedFieldsGrow)
        self.root.addLayout(self.form)
        self.root.addStretch(1)
        self.set_section("Formatting")

    def set_section(self, section: str) -> None:
        """Replace the form with the requested global setting family."""
        self.title.setText(section)
        while self.form.rowCount():
            self.form.removeRow(0)
        if section == "Comments":
            self._build_comments()
        elif section == "Output Style":
            self._build_output()
        else:
            self._build_formatting()

    def _build_formatting(self) -> None:
        """Build settings controlling generic keyword/data formatting."""
        self.description.setText(
            "Defaults applied across records unless a record-specific setting "
            "overrides them."
        )
        uppercase = QCheckBox("Uppercase generated keywords")
        uppercase.setChecked(True)
        self.form.addRow("Keyword case", uppercase)
        blank = QCheckBox("Insert a blank line between top-level blocks")
        blank.setChecked(True)
        self.form.addRow("Block spacing", blank)
        prefix = QLineEdit("*")
        self.form.addRow("Keyword prefix", prefix)
        separator = QComboBox()
        separator.addItems((", ", ",", " "))
        self.form.addRow("Option separator", separator)
        floats = QComboBox()
        floats.addItems((".6g", ".8g", ".12g", ".6f", ".12e"))
        self.form.addRow("Default float format", floats)

    def _build_comments(self) -> None:
        """Build global comment syntax controls."""
        self.description.setText(
            "Controls comments generated by the formatter itself. Record templates "
            "remain focused on solver syntax."
        )
        enabled = QCheckBox("Emit generated comments")
        enabled.setChecked(True)
        self.form.addRow("Comments", enabled)
        style = QComboBox()
        style.addItems(("** comment", "# comment", "/* comment */"))
        self.form.addRow("Comment style", style)
        heading = QCheckBox("Include OpenCAE generation heading")
        heading.setChecked(True)
        self.form.addRow("Deck heading", heading)

    def _build_output(self) -> None:
        """Build file-level output presentation controls."""
        self.description.setText(
            "Controls file-wide text output rather than individual solver records."
        )
        endings = QComboBox()
        endings.addItems(("Platform default", "LF", "CRLF"))
        self.form.addRow("Line endings", endings)
        encoding = QComboBox()
        encoding.addItems(("UTF-8", "ASCII"))
        self.form.addRow("Encoding", encoding)
        indent = QSpinBox()
        indent.setRange(0, 8)
        self.form.addRow("Indentation spaces", indent)
        trailing = QCheckBox("End file with newline")
        trailing.setChecked(True)
        self.form.addRow("Final newline", trailing)
