import {Renderer} from './renderer.js?v=20260927o';
import {ViewCube} from './view-cube.js?v=20260927o';
import {TimeManager} from './time-manager.js?v=20260927o';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],canvas=$('#gl'),workspace=$('#workspace');
const renderer=new Renderer(canvas);
const viewCube=new ViewCube($('#viewCube'),renderer);
let data=null,worker=null,currentField=null,currentDisp=null,interpMode='shape',queryMode='off',selected={node:-1,element:-1},rangeMode={min:'frame',max:'frame'},symmetric=false,playing=false,playTimer=null,pathPicking=false,pivotPicking=false,pathWaypoints=[],currentPath=[],savedPaths=[],adjacency=null,sectionBase=[0,0,0],plotMode='path',lastPlot=null,playbackRangeRestore=null,activeInterpolation=null,playbackBaseKey='';
const TYPE_NAMES={1:'Hexahedron (8-node)',2:'Wedge (6-node)',3:'Tetrahedron (4-node)',4:'Quadratic hexahedron (20-node)',5:'Quadratic wedge (15-node)',6:'Quadratic tetrahedron (10-node)',7:'Triangle (3-node)',8:'Quadratic triangle (6-node)',9:'Quadrilateral (4-node)',10:'Quadratic quadrilateral (8-node)',11:'Line (2-node)',12:'Quadratic line (3-node)'};
const PALETTES={diverging:[[0,'#313695'],[.25,'#74add1'],[.5,'#f1f3e6'],[.75,'#fdae61'],[1,'#a50026']],turbo:[[0,'#30123b'],[.2,'#4667e8'],[.4,'#1bcfd4'],[.6,'#63e55a'],[.8,'#f9b12a'],[1,'#7a0403']],viridis:[[0,'#440154'],[.25,'#3b528b'],[.5,'#21918c'],[.75,'#5ec962'],[1,'#fde725']],gray:[[0,'#151719'],[1,'#f2f4f5']]};

function showLoading(value,phase,detail=''){const o=$('#loading');o.classList.add('active');o.setAttribute('aria-hidden','false');$('#loadingBar').style.width=`${Math.max(0,Math.min(100,value))}%`;$('#loadingPercent').textContent=`${Math.round(value)}%`;$('#loadingPhase').textContent=phase;$('#loadingDetail').textContent=detail;}
function hideLoading(){const o=$('#loading');o.classList.remove('active');o.setAttribute('aria-hidden','true');}
const nextFrame=()=>new Promise(requestAnimationFrame);
function toast(message,ms=3200){const e=$('#toast');e.textContent=message;e.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.style.display='none',ms);}
function escapeHTML(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function fmt(v){if(!Number.isFinite(v))return '—';const a=Math.abs(v);return a!==0&&(a>=1e4||a<1e-3)?v.toExponential(5):v.toPrecision(7).replace(/0+$/,'').replace(/\.$/,'');}
function bytes(n){if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KiB`;return`${(n/1048576).toFixed(1)} MiB`;}
function setOptions(el,items,value){el.innerHTML=items.map(x=>`<option value="${escapeHTML(x.value)}">${escapeHTML(x.label)}</option>`).join('');if(value!=null&&items.some(x=>String(x.value)===String(value)))el.value=String(value);}
function uniqueFields(fields){const m=new Map;for(const f of fields)m.set(f.name,f);return [...m.values()];}
function steps(){return[...new Set((data?.fields||[]).map(f=>f.step))].sort((a,b)=>a-b);}
function frames(step=+$('#step').value){const m=new Map;for(const f of data?.fields||[])if(f.step===step)m.set(`${f.frame}|${f.value}`,{id:f.frame,value:f.value});return[...m.values()].sort((a,b)=>a.id-b.id||a.value-b.value);}
function fieldsInFrame(){const s=+$('#step').value,f=+$('#frame').value;return uniqueFields((data?.fields||[]).filter(x=>x.step===s&&x.frame===f));}
function derivedComponents(field){if(!field)return[];const u=field.components.map(x=>String(x).toUpperCase()),out=['Magnitude',...field.components];if(['SXX','SYY','SZZ','SXY','SYZ'].every(x=>u.includes(x))&&(u.includes('SZX')||u.includes('SXZ')))out.push('Mises');return [...new Set(out)];}
function currentComponent(){return $('#component').value;}
function currentStep(){return +$('#step').value||1;}
function currentFrame(){return +$('#frame').value||1;}
function fieldByIndex(i){return(data?.fields||[]).find(f=>f.index===+i)||null;}function fieldAt(step,frame,name){return(data?.fields||[]).find(f=>f.step===step&&f.frame===frame&&f.name===name)||null;}
function displacementFor(step=currentStep(),frame=currentFrame()){const fs=(data?.fields||[]).filter(f=>f.step===step&&f.frame===frame),valid=fs.filter(f=>{const u=f.components.map(x=>String(x).toUpperCase());return['D1','D2','D3'].every(x=>u.includes(x));});return valid.find(f=>f.name.toUpperCase().startsWith('DISP'))||valid.at(-1)||null;}

async function loadFile(file){if(!file)return;if(worker)worker.terminate();stopPlayback();showLoading(1,'Opening FRD',file.name);await nextFrame();worker=new Worker('./frd-worker.js?v=20260927o',{type:'module'});worker.onmessage=async e=>{const m=e.data;if(m.type==='progress'){showLoading(m.value,m.phase,m.detail);return;}if(m.type==='error'){hideLoading();toast(`FRD load failed: ${m.message}`,7000);worker?.terminate();worker=null;return;}if(m.type==='done'){try{showLoading(94,'Uploading GPU data','Creating compact WebGL resources');await nextFrame();data=m;renderer.load(data);showLoading(97,'Preparing results','Building frame, field and picking state');await nextFrame();resetSessionState();populate();showLoading(100,'Ready',`${data.nodeIds.length.toLocaleString()} nodes · ${data.elementIds.length.toLocaleString()} elements`);await new Promise(r=>setTimeout(r,120));hideLoading();worker?.terminate();worker=null;}catch(err){hideLoading();toast(`Viewer initialization failed: ${err.message}`,7000);console.error(err);}}};worker.onerror=e=>{hideLoading();toast(`Worker error: ${e.message}`,7000);};worker.postMessage({type:'load',file});}
function resetSessionState(){rangeMode={min:'frame',max:'frame'};symmetric=false;$('#symmetry').classList.remove('active');selected={node:-1,element:-1};queryMode='off';pathPicking=false;pathWaypoints=[];currentPath=[];savedPaths=[];adjacency=null;plotMode='path';lastPlot=null;renderer.setSelection(-1,-1);renderer.setPath([],[]);$$('#queryMode button').forEach(b=>b.classList.toggle('active',b.dataset.value==='off'));$$('#plotMode button').forEach(b=>b.classList.toggle('active',b.dataset.value==='path'));$('#pathPlotOptions').hidden=false;$('#timePlotOptions').hidden=true;$('#exportPlot').disabled=true;}
function populate(){const s=steps();$('#filemeta').textContent=`${data.file.name} · ${data.nodeIds.length.toLocaleString()} nodes · ${data.elementIds.length.toLocaleString()} elements · ${data.fields.length} result blocks · ${bytes(data.file.size)}`;$('#drop').style.display='none';$('#resultInfo').innerHTML=`<span>Nodes</span><b>${data.nodeIds.length.toLocaleString()}</b><span>Elements</span><b>${data.elementIds.length.toLocaleString()}</b><span>Result blocks</span><b>${data.fields.length.toLocaleString()}</b><span>File</span><b>${escapeHTML(bytes(data.file.size))}</b>`;if(!s.length){setOptions($('#step'),[{value:1,label:'Geometry only'}]);setOptions($('#frame'),[{value:1,label:'—'}]);setOptions($('#field'),[]);setOptions($('#component'),[]);currentField=null;currentDisp=null;renderer.setField(null,'',true);renderer.setDisplacement(null);$('#legend').style.display='none';initializeSection();return;}setOptions($('#step'),s.map((x,i)=>({value:x,label:`Step ${i+1}`})),s[0]);stepChanged(false);initializeSection();timeManager.sync(true);}
function initializeSection(){if(!renderer.bounds)return;sectionBase=[...renderer.bounds.center];setOrigin(sectionBase);setNormal([1,0,0]);$('#cutOffset').value='0';$('#cutOffsetValue').value='0%';applySection();}
function stepChanged(preserve=true){timeManager.stop(false);const oldFrame=preserve?$('#frame').value:null,fs=frames();setOptions($('#frame'),fs.map(x=>({value:x.id,label:`Frame ${x.id} — ${fmt(x.value)}`})),oldFrame||fs[0]?.id);$('#frameSlider').min='0';$('#frameSlider').max=String(Math.max(0,fs.length-1));$('#frameSlider').value=String(Math.max(0,fs.findIndex(x=>x.id===+$('#frame').value)));frameChanged(preserve);}
function frameChanged(preserve=true){activeInterpolation=null;playbackBaseKey='';renderer.clearFrameInterpolation();const oldField=preserve?currentField?.name:null,oldComp=preserve?currentComponent():null,fs=fieldsInFrame();setOptions($('#field'),fs.map(f=>({value:f.index,label:f.name})),fs.find(f=>f.name===oldField)?.index||fs[0]?.index);currentDisp=displacementFor();renderer.setDisplacement(currentDisp);currentField=fieldByIndex($('#field').value);fieldChanged(oldComp,!preserve||currentField?.name!==oldField);const frameList=frames(),idx=frameList.findIndex(x=>x.id===currentFrame());$('#frameSlider').value=String(Math.max(0,idx));applyRangeModes();refreshQuery();timeManager.sync(false);}
function fieldChanged(preferred=null,resetRange=true){activeInterpolation=null;playbackBaseKey='';renderer.clearFrameInterpolation();currentField=fieldByIndex($('#field').value);lastPlot=null;$('#exportPlot').disabled=true;if(plotMode==='time')$('#plotPath').disabled=!currentField;if(!currentField){renderer.setField(null,'',interpMode==='shape');$('#outputList').innerHTML='';$('#legend').style.display='none';return;}const comps=derivedComponents(currentField),choice=comps.includes(preferred)?preferred:(comps.includes('Magnitude')?'Magnitude':comps[0]);setOptions($('#component'),comps.map(c=>({value:c,label:c})),choice);renderOutputList();renderer.setField(currentField,currentComponent(),interpMode==='shape');if(resetRange)rangeMode={min:'frame',max:'frame'};applyRangeModes();refreshQuery();}
function componentChanged(){activeInterpolation=null;playbackBaseKey='';renderer.clearFrameInterpolation();renderer.setField(currentField,currentComponent(),interpMode==='shape');rangeMode={min:'frame',max:'frame'};applyRangeModes();renderOutputList();refreshQuery();if(plotMode==='time')$('#plotPath').disabled=!currentField;lastPlot=null;$('#exportPlot').disabled=true;}
function displayInterpolatedTime(time){if(!currentField)return;const br=timeManager.bracket(time);if(!br)return;const name=currentField.name,component=currentComponent(),shape=interpMode==='shape',left=fieldAt(currentStep(),br.left.id,name)||currentField,right=fieldAt(currentStep(),br.right.id,name)||left,leftDisp=displacementFor(currentStep(),br.left.id),rightDisp=displacementFor(currentStep(),br.right.id),baseKey=[br.left.id,name,component,shape?1:0].join(':');if(baseKey!==playbackBaseKey){renderer.setField(left,component,shape);renderer.setDisplacement(leftDisp);playbackBaseKey=baseKey;}renderer.setFrameInterpolation(right,rightDisp,component,shape,br.alpha);activeInterpolation={left,right,leftDisp,rightDisp,alpha:br.alpha,time:br.time};}
function clearInterpolatedTime(){activeInterpolation=null;playbackBaseKey='';renderer.clearFrameInterpolation();}
function boundsBetweenFields(l,r,a,component=currentComponent()){if(!l)return[0,1];if(!r||a<=1e-9)return boundsForField(l,component);const lu=l.components.map(x=>String(x).toUpperCase());if(l.width!==r.width||l.components.length!==r.components.length)return boundsForField(l,component);let mn=Infinity,mx=-Infinity;const direct=l.components.indexOf(component),all=component==='Magnitude'?lu.indexOf('ALL'):-1,mises=component==='Mises',stress=mises?[lu.indexOf('SXX'),lu.indexOf('SYY'),lu.indexOf('SZZ'),lu.indexOf('SXY'),lu.indexOf('SYZ'),Math.max(lu.indexOf('SZX'),lu.indexOf('SXZ'))]:null;for(let n=0;n<data.nodeIds.length;n++){let v=NaN;if(direct>=0){const x=l.values[n*l.width+direct],y=r.values[n*r.width+direct];if(Number.isFinite(x)&&Number.isFinite(y))v=x+(y-x)*a;}else if(all>=0){const x=l.values[n*l.width+all],y=r.values[n*r.width+all];if(Number.isFinite(x)&&Number.isFinite(y))v=Math.abs(x+(y-x)*a);}else if(mises&&stress.every(k=>k>=0)){const q=stress.map(k=>{const x=l.values[n*l.width+k],y=r.values[n*r.width+k];return x+(y-x)*a;});if(q.every(Number.isFinite)){const[x,y,z,xy,yz,zx]=q;v=Math.sqrt(Math.max(.5*((x-y)**2+(y-z)**2+(z-x)**2)+3*(xy*xy+yz*yz+zx*zx),0));}}else if(component==='Magnitude'){let ss=0,ok=true,count=Math.min(l.name.toUpperCase().startsWith('DISP')?3:l.width,8);for(let k=0;k<count;k++){const x=l.values[n*l.width+k],y=r.values[n*r.width+k];if(!Number.isFinite(x)||!Number.isFinite(y)){ok=false;break;}const q=x+(y-x)*a;ss+=q*q;}if(ok)v=Math.sqrt(ss);}if(Number.isFinite(v)){mn=Math.min(mn,v);mx=Math.max(mx,v);}}if(mn===Infinity)return boundsForField(l,component);if(component==='Magnitude'||component==='Mises')mn=0;if(mn===mx)mx=mn+Math.max(Math.abs(mn),1)*1e-12;return[mn,mx];}
function interpolatedBounds(){if(!activeInterpolation)return boundsForField(currentField,currentComponent());return boundsBetweenFields(activeInterpolation.left,activeInterpolation.right,activeInterpolation.alpha,currentComponent());}
function boundsAtPlaybackTime(time){if(!currentField)return[0,1];const br=timeManager.bracket(time);if(!br)return boundsForField(currentField,currentComponent());const left=fieldAt(currentStep(),br.left.id,currentField.name)||currentField,right=fieldAt(currentStep(),br.right.id,currentField.name)||left;return boundsBetweenFields(left,right,br.alpha,currentComponent());}

function renderOutputList(){if(!currentField){$('#outputList').innerHTML='';return;}$('#outputList').innerHTML=derivedComponents(currentField).map(c=>`<div class="outputItem ${c===currentComponent()?'active':''}" data-component="${escapeHTML(c)}"><span>${escapeHTML(c)}</span><small>${escapeHTML(currentField.name)}</small></div>`).join('');$$('#outputList .outputItem').forEach(e=>e.onclick=()=>{$('#component').value=e.dataset.component;componentChanged();});}

function scalarAccessor(field,component){if(!field)return()=>NaN;const comps=field.components,u=comps.map(x=>String(x).toUpperCase());if(component==='Magnitude'){const all=u.indexOf('ALL');if(all>=0)return i=>field.values[i*field.width+all];const count=Math.max(1,Math.min(field.name.toUpperCase().startsWith('DISP')?3:field.width,8));return i=>{let s=0,ok=false;for(let j=0;j<count;j++){const v=field.values[i*field.width+j];if(Number.isFinite(v)){s+=v*v;ok=true;}}return ok?Math.sqrt(s):NaN;};}if(component==='Mises'){const ix=[u.indexOf('SXX'),u.indexOf('SYY'),u.indexOf('SZZ'),u.indexOf('SXY'),u.indexOf('SYZ'),Math.max(u.indexOf('SZX'),u.indexOf('SXZ'))];return i=>{const v=ix.map(j=>j>=0?field.values[i*field.width+j]:NaN);if(v.some(x=>!Number.isFinite(x)))return NaN;const[a,b,c,d,e,f]=v;return Math.sqrt(Math.max(.5*((a-b)**2+(b-c)**2+(c-a)**2)+3*(d*d+e*e+f*f),0));};}const k=comps.indexOf(component);return i=>k>=0?field.values[i*field.width+k]:NaN;}
function boundsForField(field,component){const get=scalarAccessor(field,component);let mn=Infinity,mx=-Infinity;for(let i=0;i<data.nodeIds.length;i++){const v=get(i);if(Number.isFinite(v)){if(v<mn)mn=v;if(v>mx)mx=v;}}if(mn===Infinity)return[0,1];if(component==='Magnitude'||component==='Mises')mn=0;if(mn===mx)mx=mn+Math.max(Math.abs(mn),1)*1e-12;return[mn,mx];}
function allFrameBounds(){if(!currentField)return[0,1];let mn=Infinity,mx=-Infinity;for(const f of data.fields){if(f.step!==currentStep()||f.name!==currentField.name)continue;const[b0,b1]=boundsForField(f,currentComponent());mn=Math.min(mn,b0);mx=Math.max(mx,b1);}return mn===Infinity?[0,1]:[mn,mx];}
function applyRangeModes(){if(!currentField)return;const frame=boundsForField(currentField,currentComponent()),all=(rangeMode.min==='all'||rangeMode.max==='all')?allFrameBounds():null;if(rangeMode.min==='frame')$('#min').value=frame[0];else if(rangeMode.min==='all')$('#min').value=all[0];if(rangeMode.max==='frame')$('#max').value=frame[1];else if(rangeMode.max==='all')$('#max').value=all[1];if(symmetric){const m=Math.max(Math.abs(+$('#min').value),Math.abs(+$('#max').value));$('#min').value=-m;$('#max').value=m;}applyContour();}
function setBound(which,scope){const b=scope==='all'?allFrameBounds():boundsForField(currentField,currentComponent());rangeMode[which]=scope;$('#'+(which==='min'?'min':'max')).value=which==='min'?b[0]:b[1];if(symmetric){const m=Math.max(Math.abs(+$('#min').value),Math.abs(+$('#max').value));$('#min').value=-m;$('#max').value=m;}applyContour();}
function applyContour(){const continuous=false,outside=$('#outsideColors').checked;$('#belowColor').disabled=!outside;$('#aboveColor').disabled=!outside;let mn=+$('#min').value,mx=+$('#max').value;if(!Number.isFinite(mn)||!Number.isFinite(mx))return;if(mn>mx)[mn,mx]=[mx,mn];const levels=+$('#levels').value,palette={diverging:0,turbo:1,viridis:2,gray:3}[$('#palette').value]??0;renderer.setRange({min:mn,max:mx,levels,continuous,palette,outside,below:hexRGB($('#belowColor').value),above:hexRGB($('#aboveColor').value)});updateLegend(mn,mx);}
function hexRGB(h){const n=parseInt(h.slice(1),16);return[(n>>16&255)/255,(n>>8&255)/255,(n&255)/255];}
function paletteCSS(horizontal=false){const name=$('#palette').value,levels=+$('#levels').value,dir=horizontal?'90deg':'to top',stops=[];for(let i=0;i<levels;i++){const c=samplePalette(name,(i+.5)/levels),a=i/levels*100,b=(i+1)/levels*100;stops.push(`${c} ${a}%`,`${c} ${b}%`);}return`linear-gradient(${dir},${stops.join(',')})`;}
function samplePalette(name,t){const s=PALETTES[name];let i=0;while(i<s.length-2&&t>s[i+1][0])i++;const[a,ca]=s[i],[b,cb]=s[i+1],u=(t-a)/Math.max(b-a,1e-12),A=parseHex(ca),B=parseHex(cb),v=A.map((x,k)=>Math.round(x+(B[k]-x)*u));return`#${v.map(x=>x.toString(16).padStart(2,'0')).join('')}`;}
function parseHex(h){const n=parseInt(h.slice(1),16);return[n>>16&255,n>>8&255,n&255];}
function updateLegend(mn=+$('#min').value,mx=+$('#max').value){const show=!!currentField&&$('#showLegend').checked,el=$('#legend');el.style.display=show?'block':'none';el.classList.toggle('left',$('#legendPosition').value==='left');$('#legendTitle').textContent=currentField?`${currentField.name} · ${currentComponent()}`:'Result';$('#legendBar').style.background=paletteCSS(false);$('#colorPreview').style.background=paletteCSS(true);const ticks=[];for(let i=0;i<5;i++){const t=1-i/4;ticks.push(`<span>${escapeHTML(fmt(mn+(mx-mn)*t))}</span>`);}$('#legendTicks').innerHTML=ticks.join('');}

function applyDisplay(){renderer.setDisplay({meshLines:$('#meshLines').checked,boundary:$('#boundary').checked,undeformed:$('#undeformed').checked,deformed:$('#deformOn').checked,deformScale:Math.max(0,+$('#deformScale').value||0),shape:interpMode==='shape'});refreshQuery();}
function setInterpolation(mode){interpMode=mode;$$('#interp button').forEach(b=>b.classList.toggle('active',b.dataset.value===mode));$('#quality').disabled=mode!=='shape';$('#qualityValue').classList.toggle('disabled',mode!=='shape');renderer.setField(currentField,currentComponent(),mode==='shape');applyDisplay();}
function autoDeformCurrent(){const s=renderer.autoDeformScale(currentDisp);if(s==null)return toast('No displacement field is available in this frame.');$('#deformScale').value=String(s);$('#deformOn').checked=true;applyDisplay();}
function autoDeformAll(){let m=0;for(const f of data.fields){if(f.step!==currentStep())continue;const u=f.components.map(x=>String(x).toUpperCase());if(['D1','D2','D3'].every(x=>u.includes(x)))m=Math.max(m,renderer.maxDisplacement(f));}if(m<=1e-14)return toast('No displacement values are available in this step.');$('#deformScale').value=String(.1*(renderer.bounds.radius*2)/m);$('#deformOn').checked=true;applyDisplay();}

function setOrigin(v){$('#originX').value=String(v[0]);$('#originY').value=String(v[1]);$('#originZ').value=String(v[2]);}
function setNormal(v){$('#normalX').value=String(v[0]);$('#normalY').value=String(v[1]);$('#normalZ').value=String(v[2]);}
function origin(){return[+$('#originX').value||0,+$('#originY').value||0,+$('#originZ').value||0];}function normal(){const v=[+$('#normalX').value||0,+$('#normalY').value||0,+$('#normalZ').value||0],l=Math.hypot(...v)||1;return v.map(x=>x/l);}
function applySection(){renderer.setSection({enabled:$('#cutOn').checked,showPlane:$('#showPlane').checked,invert:$('#cutInvert').checked,origin:origin(),normal:normal()});}
function chooseAxis(axis){const n=axis==='x'?[1,0,0]:axis==='y'?[0,1,0]:[0,0,1];setNormal(n);sectionBase=[...renderer.displayBounds().center];setOrigin(sectionBase);$('#cutOffset').value='0';$('#cutOffsetValue').value='0%';$$('.axisButtons button').forEach(b=>b.classList.toggle('active',b.dataset.axis===axis));applySection();}
function offsetSection(){const t=+$('#cutOffset').value||0,n=normal(),r=renderer.bounds.radius*1.2,p=sectionBase.map((x,i)=>x+n[i]*r*t);setOrigin(p);$('#cutOffsetValue').value=`${Math.round(t*100)}%`;applySection();}

function setPivotPicking(active){pivotPicking=!!active;$('#pickPivot').classList.toggle('active',pivotPicking);$('#viewport').classList.toggle('pivotPicking',pivotPicking);if(pivotPicking){if(pathPicking){pathPicking=false;renderWaypoints();}queryMode='off';$('#queryMode button').forEach(b=>b.classList.toggle('active',b.dataset.value==='off'));$('#statusHint').textContent='Click a visible point to set the rotation center · Esc cancels';}else $('#statusHint').textContent=pathPicking?'LMB drag orbit · click nodes to add path waypoints':queryMode==='off'?'LMB orbit · MMB pan · wheel zoom':`LMB drag orbit · click to query ${queryMode}`;}
function setPathPicking(active){if(active&&pivotPicking)setPivotPicking(false);pathPicking=!!active;if(pathPicking){queryMode='off';$('#queryMode button').forEach(b=>b.classList.toggle('active',b.dataset.value==='off'));$('#statusHint').textContent='LMB drag orbit · click nodes to add path waypoints';}else $('#statusHint').textContent=queryMode==='off'?'LMB orbit · MMB pan · wheel zoom':`LMB drag orbit · click to query ${queryMode}`;renderWaypoints();}
function setQueryMode(mode){if(mode!=='off'&&pivotPicking)setPivotPicking(false);queryMode=mode;if(pathPicking)pathPicking=false;$('#queryMode button').forEach(b=>b.classList.toggle('active',b.dataset.value===mode));$('#statusHint').textContent=mode==='off'?'LMB orbit · MMB pan · wheel zoom':`LMB drag orbit · click to query ${mode}`;renderWaypoints();}
function clearSelection(){selected={node:-1,element:-1};renderer.setSelection(-1,-1);$('#queryResult').className='queryResult empty';$('#queryResult').textContent='No selection';}
function pickNode(index,forPath=false){if(index<0)return;if(forPath){if(pathWaypoints.at(-1)!==index)pathWaypoints.push(index);if(pathWaypoints.length>=2)buildPath(true);else{currentPath=[index];renderer.setPath(currentPath,pathWaypoints);renderWaypoints();$('#savePath').disabled=true;if(plotMode==='path')$('#plotPath').disabled=true;}return;}selected={node:index,element:-1};renderer.setSelection(index,-1);const id=data.nodeIds[index],p=nodeDisplayedPosition(index),rows=currentField?fieldRows(index):[];$('#timeNode').value=String(id);$('#queryResult').className='queryResult';$('#queryResult').innerHTML=`<strong>Node ${id}</strong><div>Coordinates: (${p.map(fmt).join(', ')})</div>${rows.length?`<table><thead><tr><th>Component</th><th>Value</th></tr></thead><tbody>${rows.map(([a,b])=>`<tr><td>${escapeHTML(a)}</td><td>${escapeHTML(fmt(b))}</td></tr>`).join('')}</tbody></table>`:''}`;}
function pickElement(index){if(index<0)return;selected={node:-1,element:index};renderer.setSelection(-1,index);const o0=data.elementOffsets[index],o1=data.elementOffsets[index+1],nodes=[...data.elementConnectivity.subarray(o0,o1)],id=data.elementIds[index],type=data.elementTypes[index],get=currentField?scalarAccessor(currentField,currentComponent()):null;$('#queryResult').className='queryResult';$('#queryResult').innerHTML=`<strong>Element ${id}</strong><div>${escapeHTML(TYPE_NAMES[type]||`FRD type ${type}`)}</div><table><thead><tr><th>Node</th><th>${escapeHTML(currentComponent()||'Value')}</th></tr></thead><tbody>${nodes.map(i=>`<tr><td>${data.nodeIds[i]}</td><td>${escapeHTML(get?fmt(get(i)):'—')}</td></tr>`).join('')}</tbody></table>`;}
function nodeDisplayedPosition(i){const p=[data.positions[i*3],data.positions[i*3+1],data.positions[i*3+2]];if(!$('#deformOn').checked||!currentDisp)return p;const u=currentDisp.components.map(x=>String(x).toUpperCase()),ix=['D1','D2','D3'].map(x=>u.indexOf(x)),s=+$('#deformScale').value||0;return p.map((x,k)=>x+(ix[k]>=0?(currentDisp.values[i*currentDisp.width+ix[k]]||0)*s:0));}
function fieldRows(i){const out=currentField.components.map((c,j)=>[c,currentField.values[i*currentField.width+j]]);for(const c of derivedComponents(currentField).filter(x=>!currentField.components.includes(x)))out.push([c,scalarAccessor(currentField,c)(i)]);return out;}
function refreshQuery(){if(selected.node>=0)pickNode(selected.node);else if(selected.element>=0)pickElement(selected.element);}

function buildAdjacency(){if(adjacency)return adjacency;adjacency=Array.from({length:data.nodeIds.length},()=>[]);const p=data.positions,s=data.geometry.pathSegments;for(let i=0;i<s.length;i+=2){const a=s[i],b=s[i+1],d=Math.hypot(p[a*3]-p[b*3],p[a*3+1]-p[b*3+1],p[a*3+2]-p[b*3+2]);adjacency[a].push([b,d]);adjacency[b].push([a,d]);}return adjacency;}
function shortestPath(start,end){if(start===end)return[start];const adj=buildAdjacency(),dist=new Float64Array(adj.length);dist.fill(Infinity);dist[start]=0;const prev=new Int32Array(adj.length);prev.fill(-1);const seen=new Uint8Array(adj.length),heap=[[0,start]],push=item=>{heap.push(item);let i=heap.length-1;while(i){const p=(i-1)>>1;if(heap[p][0]<=item[0])break;heap[i]=heap[p];i=p;}heap[i]=item;},pop=()=>{const root=heap[0],last=heap.pop();if(heap.length){let i=0;while(true){let a=i*2+1;if(a>=heap.length)break;let b=a+1,c=b<heap.length&&heap[b][0]<heap[a][0]?b:a;if(heap[c][0]>=last[0])break;heap[i]=heap[c];i=c;}heap[i]=last;}return root;};while(heap.length){const[d,u]=pop();if(seen[u])continue;seen[u]=1;if(u===end){const r=[end];while(r.at(-1)!==start){const p=prev[r.at(-1)];if(p<0)break;r.push(p);}if(r.at(-1)===start)return r.reverse();break;}for(const[v,w]of adj[u]){const nd=d+w;if(nd<dist[v]-1e-12){dist[v]=nd;prev[v]=u;push([nd,v]);}}}throw new Error(`No connected mesh-edge route between nodes ${data.nodeIds[start]} and ${data.nodeIds[end]}`);}
function buildPath(quiet=false){if(pathWaypoints.length<2){currentPath=pathWaypoints.length?[pathWaypoints[0]]:[];renderer.setPath(currentPath,pathWaypoints);renderWaypoints();return;}try{const out=[];for(let i=1;i<pathWaypoints.length;i++){const seg=shortestPath(pathWaypoints[i-1],pathWaypoints[i]);out.push(...(out.length?seg.slice(1):seg));}currentPath=out;renderer.setPath(currentPath,pathWaypoints);if(plotMode==='path')$('#plotPath').disabled=!currentPath.length;$('#savePath').disabled=!currentPath.length;renderWaypoints();if(!quiet)toast(`Path updated with ${currentPath.length} mesh nodes.`);}catch(e){toast(e.message,5000);}}
function removeWaypoint(index){pathWaypoints.splice(index,1);if(pathWaypoints.length>=2)buildPath(true);else{currentPath=pathWaypoints.length?[pathWaypoints[0]]:[];renderer.setPath(currentPath,pathWaypoints);renderWaypoints();const ready=pathWaypoints.length>=2&&currentPath.length>=2;if(plotMode==='path')$('#plotPath').disabled=!ready;$('#savePath').disabled=!ready;}}
function renderWaypoints(){const el=$('#pathWaypoints');if(!el)return;el.className='pathList waypointList';const rows=pathWaypoints.map((node,k)=>`<div class="pathRow waypointRow"><span><b>${k+1}</b> · Node ${data?data.nodeIds[node]:node}</span><button class="waypointRemove" data-waypoint="${k}" title="Remove waypoint" aria-label="Remove waypoint">−</button></div>`).join('');const add=`<button id="waypointAddSlot" class="waypointAddSlot ${pathPicking?'active':''}" type="button"><span class="waypointAddIcon">${pathPicking?'×':'+'}</span><span>${pathPicking?'Stop picking':'Add waypoint'}</span></button>`;el.innerHTML=rows+add;el.querySelectorAll('.waypointRemove').forEach(b=>b.onclick=e=>{e.stopPropagation();removeWaypoint(+b.dataset.waypoint);});$('#waypointAddSlot').onclick=()=>setPathPicking(!pathPicking);}
function saveCurrentPath(){if(!currentPath.length)return;const name=$('#pathName').value.trim()||`Path ${savedPaths.length+1}`;if(savedPaths.some(p=>p.name===name))return toast(`A path named ${name} already exists.`);savedPaths.push({name,waypoints:[...pathWaypoints],nodes:[...currentPath],xAxis:$('#pathXAxis').value});renderSavedPaths();}
function renderSavedPaths(){const el=$('#savedPaths');if(!savedPaths.length){el.className='pathList empty';el.textContent='No saved paths';return;}el.className='pathList';el.innerHTML=savedPaths.map((p,i)=>`<div class="pathRow"><button data-load="${i}">${escapeHTML(p.name)} · ${p.nodes.length} nodes</button><button data-delete="${i}">×</button></div>`).join('');$$('[data-load]').forEach(b=>b.onclick=()=>{const p=savedPaths[+b.dataset.load];pathWaypoints=[...p.waypoints];currentPath=[...p.nodes];$('#pathName').value=p.name;if(p.xAxis)$('#pathXAxis').value=p.xAxis;renderer.setPath(currentPath,pathWaypoints);renderWaypoints();if(plotMode==='path')$('#plotPath').disabled=false;$('#savePath').disabled=false;});$$('[data-delete]').forEach(b=>b.onclick=()=>{savedPaths.splice(+b.dataset.delete,1);renderSavedPaths();});}
function setPlotMode(mode){plotMode=mode;$$('#plotMode button').forEach(b=>b.classList.toggle('active',b.dataset.value===mode));$('#pathPlotOptions').hidden=mode!=='path';$('#timePlotOptions').hidden=mode!=='time';$('#plotPath').disabled=mode==='path'?!currentPath.length:!currentField;lastPlot=null;$('#exportPlot').disabled=true;}
function plotPath(){if(!currentField)return toast('Select an output first.');const component=currentComponent();let x=[],y=[],xlabel='',title='';if(plotMode==='path'){if(!currentPath.length)return toast('Build or load a path first.');const get=scalarAccessor(currentField,component),p=data.positions,useNode=$('#pathXAxis').value==='node';let d=0;for(let i=0;i<currentPath.length;i++){const ni=currentPath[i];if(i){const a=currentPath[i-1];d+=Math.hypot(p[ni*3]-p[a*3],p[ni*3+1]-p[a*3+1],p[ni*3+2]-p[a*3+2]);}const v=get(ni);if(Number.isFinite(v)){x.push(useNode?data.nodeIds[ni]:d);y.push(v);}}xlabel=useNode?'Node ID':'Distance';title=`${$('#pathName').value||'Path'} · ${currentField.name}:${component}`;}else{const nodeId=Math.trunc(+$('#timeNode').value),ni=data.nodeIds.findIndex(v=>v===nodeId);if(!Number.isFinite(nodeId)||ni<0)return toast('Enter a node ID that exists in this result mesh.');const fields=data.fields.filter(f=>f.step===currentStep()&&f.name===currentField.name).sort((a,b)=>a.frame-b.frame||a.value-b.value),seen=new Set;for(const f of fields){if(seen.has(f.frame))continue;seen.add(f.frame);const v=scalarAccessor(f,component)(ni);if(Number.isFinite(v)){x.push(f.value);y.push(v);}}xlabel='Time / solver frame value';title=`Node ${nodeId} · ${currentField.name}:${component}`;}if(!x.length)return toast('The selected output has no finite samples for this plot.');lastPlot={x:[...x],y:[...y],xlabel,ylabel:`${currentField.name}:${component}`,title};$('#plotTitle').textContent=title;$('#plotMeta').textContent=`${x.length} samples · X: ${xlabel}`;$('#plotModal').classList.add('active');$('#plotModal').setAttribute('aria-hidden','false');$('#exportPlot').disabled=false;requestAnimationFrame(()=>drawPlot(x,y,xlabel,lastPlot.ylabel));}
function exportPlot(){if(!lastPlot)return toast('Build a plot before exporting.');const rows=[[lastPlot.xlabel,lastPlot.ylabel],...lastPlot.x.map((x,i)=>[x,lastPlot.y[i]])],csv=rows.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\r\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${(lastPlot.title||'plot').replace(/[^a-z0-9._-]+/gi,'-')}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function drawPlot(x,y,xlabel,ylabel){const c=$('#plotCanvas'),d=Math.min(devicePixelRatio||1,2),r=c.getBoundingClientRect();c.width=Math.max(1,r.width*d);c.height=Math.max(1,r.height*d);const g=c.getContext('2d');g.scale(d,d);const w=r.width,h=r.height,pad={l:66,r:22,t:24,b:50},mnX=Math.min(...x),mxX=Math.max(...x),mnY=Math.min(...y),mxY=Math.max(...y),sx=v=>pad.l+(v-mnX)/Math.max(mxX-mnX,1e-12)*(w-pad.l-pad.r),sy=v=>h-pad.b-(v-mnY)/Math.max(mxY-mnY,1e-12)*(h-pad.t-pad.b);g.clearRect(0,0,w,h);g.strokeStyle='#343b42';g.fillStyle='#8a949d';g.font='10px system-ui';for(let i=0;i<=5;i++){const ty=pad.t+i*(h-pad.t-pad.b)/5,v=mxY-(mxY-mnY)*i/5;g.beginPath();g.moveTo(pad.l,ty);g.lineTo(w-pad.r,ty);g.stroke();g.fillText(fmt(v),6,ty+3);}g.strokeStyle='#e0e4e7';g.lineWidth=1.5;g.beginPath();x.forEach((v,i)=>{const X=sx(v),Y=sy(y[i]);i?g.lineTo(X,Y):g.moveTo(X,Y)});g.stroke();g.fillStyle='#9da6ad';g.fillText(xlabel,w/2-20,h-12);g.save();g.translate(14,h/2+20);g.rotate(-Math.PI/2);g.fillText(ylabel,0,0);g.restore();}

function startPlayback(){timeManager.play();}function stopPlayback(){timeManager.stop(false);}function togglePlayback(){timeManager.toggle();}function schedulePlay(){}


function contourAutoBounds(){if(timeManager?.mode==='across'){const b=timeManager.envelopeBounds();if(b)return b;}return interpolatedBounds();}
function refreshPlaybackAutoContour(){let changed=false;if(timeManager?.mode==='across'){const b=timeManager.envelopeBounds();if(!b)return;if(rangeMode.min==='playback'){$('#min').value=b[0];changed=true;}if(rangeMode.max==='playback'){$('#max').value=b[1];changed=true;}}else{const b=interpolatedBounds();if(rangeMode.min==='playback'){rangeMode.min='frame';$('#min').value=b[0];changed=true;}if(rangeMode.max==='playback'){rangeMode.max='frame';$('#max').value=b[1];changed=true;}}if(changed){if(symmetric){const m=Math.max(Math.abs(+$('#min').value),Math.abs(+$('#max').value));$('#min').value=-m;$('#max').value=m;}applyContour();}}
function fitAnimationEnvelope(){const b=timeManager.envelopeBounds();if(!b)return;let [mn,mx]=b;if(symmetric){const m=Math.max(Math.abs(mn),Math.abs(mx));mn=-m;mx=m;}rangeMode={min:'manual',max:'manual'};$('#min').value=mn;$('#max').value=mx;applyContour();}
const timeManager=new TimeManager({
  renderer,
  getData:()=>data,
  getFrames:()=>frames(),
  getCurrentFrame:()=>currentFrame(),
  selectFrame:id=>{if(!data)return;$('#frame').value=String(id);frameChanged(true);},
  getCurrentField:()=>currentField,
  getCurrentComponent:()=>currentComponent(),
  getCurrentStep:()=>currentStep(),
  boundsForField,
  boundsAtTime:boundsAtPlaybackTime,
  displayTime:displayInterpolatedTime,
  clearInterpolation:clearInterpolatedTime,
  isInterpolated:()=>!!activeInterpolation&&activeInterpolation.alpha>1e-9&&activeInterpolation.alpha<1-1e-9,
  captureContour:()=>({mode:{...rangeMode},min:+$('#min').value,max:+$('#max').value}),
  restoreContour:state=>{if(!state)return;rangeMode={...state.mode};$('#min').value=state.min;$('#max').value=state.max;applyRangeModes();},
  onPlaybackStart:bounds=>{if(!bounds)return;playbackRangeRestore={mode:{...rangeMode},min:+$('#min').value,max:+$('#max').value};let mn=+$('#min').value,mx=+$('#max').value;if(rangeMode.min!=='manual')mn=bounds[0];if(rangeMode.max!=='manual')mx=bounds[1];rangeMode={min:'manual',max:'manual'};$('#min').value=mn;$('#max').value=mx;applyContour();},
  onPlaybackStop:restore=>{if(restore&&playbackRangeRestore){rangeMode={...playbackRangeRestore.mode};$('#min').value=playbackRangeRestore.min;$('#max').value=playbackRangeRestore.max;applyRangeModes();}playbackRangeRestore=null;},onRangeChanged:refreshPlaybackAutoContour
});

function openPanel(name){if(name!=='paths'&&pathPicking)setPathPicking(false);const btn=$(`.rail button[data-panel="${name}"]`),panel=$(`#panel-${name}`),was=panel.classList.contains('active');$$('.panel').forEach(p=>p.classList.remove('active'));$$('.rail button').forEach(b=>b.classList.remove('active'));if(was){workspace.classList.remove('inspectorOpen');if(name==='paths'&&pathPicking)setPathPicking(false);return;}panel.classList.add('active');btn.classList.add('active');workspace.classList.add('inspectorOpen');if(name==='paths')renderWaypoints();setTimeout(()=>renderer.render(),170);}
function closePanel(){workspace.classList.remove('inspectorOpen');$$('.panel').forEach(p=>p.classList.remove('active'));$$('.rail button').forEach(b=>b.classList.remove('active'));setTimeout(()=>renderer.render(),170);}
function updateTriad(){const e=$('#axisTriad'),basis=renderer.cameraBasis(),axes=[['x',[1,0,0]],['y',[0,1,0]],['z',[0,0,1]]];for(const[name,a]of axes){const sx=a[0]*basis.right[0]+a[1]*basis.right[1]+a[2]*basis.right[2],sy=-(a[0]*basis.up[0]+a[1]*basis.up[1]+a[2]*basis.up[2]),el=e.querySelector('.'+name),cx=29,cy=29,L=21,x=cx+sx*L,y=cy+sy*L;el.style.left=`${x}px`;el.style.top=`${y}px`;let line=e.querySelector(`i.${name}`);if(!line){line=document.createElement('i');line.className=name;e.appendChild(line);}line.style.width=`${Math.hypot(sx,sy)*L}px`;line.style.transform=`translate(${cx}px,${cy}px) rotate(${Math.atan2(sy,sx)}rad)`;}}
renderer.onRender=()=>{updateTriad();viewCube.draw();};renderer.onPivot=(show,p)=>{const e=$('#pivot');e.style.display=show?'block':'none';if(show){e.style.left=`${p[0]}px`;e.style.top=`${p[1]}px`;}};

$('#file').onchange=e=>loadFile(e.target.files[0]);$('#cancelLoad').onclick=()=>{worker?.terminate();worker=null;hideLoading();toast('FRD loading cancelled.');};const viewport=$('#viewport');viewport.ondragover=e=>{e.preventDefault();};viewport.ondrop=e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f)loadFile(f);};
$$('.rail button[data-panel]').forEach(b=>b.onclick=()=>openPanel(b.dataset.panel));$$('.closePanel').forEach(b=>b.onclick=closePanel);
$('#step').onchange=()=>stepChanged(false);$('#frame').onchange=()=>frameChanged(true);$('#field').onchange=()=>fieldChanged();$('#component').onchange=componentChanged;$('#prev').onclick=()=>{const fs=frames(),i=fs.findIndex(x=>x.id===currentFrame());if(i>0){$('#frame').value=String(fs[i-1].id);frameChanged(true);}};$('#next').onclick=()=>{const fs=frames(),i=fs.findIndex(x=>x.id===currentFrame());if(i<fs.length-1){$('#frame').value=String(fs[i+1].id);frameChanged(true);}};$('#frameSlider').oninput=e=>{const fs=frames(),f=fs[+e.target.value];if(f){$('#frame').value=String(f.id);frameChanged(true);}};$('#play').onclick=togglePlayback;$('#fps').onchange=()=>{if(playing){stopPlayback();startPlayback();}};
for(const id of['meshLines','boundary','undeformed','deformOn'])$('#'+id).onchange=applyDisplay;$('#deformScale').onchange=applyDisplay;$$('#interp button').forEach(b=>b.onclick=()=>setInterpolation(b.dataset.value));$('#quality').oninput=e=>{$('#qualityValue').value=e.target.value;renderer.setQuality(+e.target.value);};$('#deformAutoFrame').onclick=autoDeformCurrent;$('#deformAutoAll').onclick=autoDeformAll;$('#deformReset').onclick=()=>{$('#deformScale').value='1';applyDisplay();};
$('#min').onchange=()=>{rangeMode.min='manual';if(symmetric){const m=Math.abs(+$('#min').value);$('#min').value=-m;$('#max').value=m;rangeMode.max='manual';}applyContour();};$('#max').onchange=()=>{rangeMode.max='manual';if(symmetric){const m=Math.abs(+$('#max').value);$('#min').value=-m;$('#max').value=m;rangeMode.min='manual';}applyContour();};$('#minAuto').onclick=()=>{const b=contourAutoBounds();rangeMode.min=timeManager.mode==='across'?'playback':'frame';$('#min').value=b[0];if(symmetric){const m=Math.max(Math.abs(+$('#min').value),Math.abs(+$('#max').value));$('#min').value=-m;$('#max').value=m;}applyContour();};$('#maxAuto').onclick=()=>{const b=contourAutoBounds();rangeMode.max=timeManager.mode==='across'?'playback':'frame';$('#max').value=b[1];if(symmetric){const m=Math.max(Math.abs(+$('#min').value),Math.abs(+$('#max').value));$('#min').value=-m;$('#max').value=m;}applyContour();};$('#symmetry').onclick=()=>{symmetric=!symmetric;$('#symmetry').classList.toggle('active',symmetric);if(symmetric){const m=Math.max(Math.abs(+$('#min').value),Math.abs(+$('#max').value));$('#min').value=-m;$('#max').value=m;rangeMode={min:'manual',max:'manual'};}applyContour();};for(const id of['outsideColors','showLegend'])$('#'+id).onchange=applyContour;for(const id of['levels','palette','belowColor','aboveColor','legendPosition'])$('#'+id).oninput=()=>{if(id==='levels')$('#levelValue').value=$('#levels').value;applyContour();};
$$('#queryMode button').forEach(b=>b.onclick=()=>setQueryMode(b.dataset.value));$('#clearSelection').onclick=clearSelection;for(const id of['cutOn','showPlane','cutInvert'])$('#'+id).onchange=applySection;$$('.axisButtons button').forEach(b=>b.onclick=()=>chooseAxis(b.dataset.axis));for(const id of['originX','originY','originZ','normalX','normalY','normalZ'])$('#'+id).onchange=()=>{sectionBase=origin();$('#cutOffset').value='0';$('#cutOffsetValue').value='0%';applySection();};$('#cutOffset').oninput=offsetSection;$('#cutCenter').onclick=()=>{sectionBase=[...renderer.displayBounds().center];setOrigin(sectionBase);$('#cutOffset').value='0';$('#cutOffsetValue').value='0%';applySection();};
$('#savePath').onclick=saveCurrentPath;$$('#plotMode button').forEach(b=>b.onclick=()=>setPlotMode(b.dataset.value));$('#plotPath').onclick=plotPath;$('#exportPlot').onclick=exportPlot;$('#closePlot').onclick=()=>{$('#plotModal').classList.remove('active');$('#plotModal').setAttribute('aria-hidden','true');};
$('#fit').onclick=()=>renderer.fit();$('#projection').onclick=()=>$('#projection').classList.toggle('active',renderer.toggleProjection());$('#pickPivot').onclick=()=>setPivotPicking(!pivotPicking);$('#screenshot').onclick=()=>{if(!data)return;const a=document.createElement('a');a.href=renderer.screenshot();a.download=`${data.file.name.replace(/\.frd$/i,'')}-viewport.png`;a.click();};
canvas.oncontextmenu=e=>e.preventDefault();canvas.onauxclick=e=>e.preventDefault();canvas.onpointerdown=e=>{if(e.button>2)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);renderer.pointerDown(e);};canvas.onpointermove=e=>renderer.pointerMove(e);canvas.onpointerup=e=>{const click=renderer.pointerUp();if(click&&data){if(pivotPicking){const p=renderer.pickWorldPoint(e.clientX,e.clientY);if(p){renderer.setRotationCenter(p);setPivotPicking(false);setTimeout(()=>{const q=renderer.projectPivot();renderer.onPivot(true,q);setTimeout(()=>renderer.onPivot(false,q),650);},190);}else toast('No visible surface under the cursor.');}else if(pathPicking){const i=renderer.pick('node',e.clientX,e.clientY);if(i>=0)pickNode(i,true);}else if(queryMode==='node'){const i=renderer.pick('node',e.clientX,e.clientY);if(i>=0)pickNode(i);}else if(queryMode==='element'){const i=renderer.pick('element',e.clientX,e.clientY);if(i>=0)pickElement(i);}}};canvas.onpointercancel=()=>renderer.pointerUp();canvas.onwheel=e=>{e.preventDefault();if(data)renderer.wheel(e);};window.onresize=()=>renderer.render();
window.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(document.activeElement?.tagName))return;if(e.key.toLowerCase()==='f'){e.preventDefault();renderer.fit();}else if(e.key==='1')renderer.setView('front');else if(e.key==='2')renderer.setView('back');else if(e.key==='3')renderer.setView('left');else if(e.key==='4')renderer.setView('right');else if(e.key==='5')renderer.setView('top');else if(e.key==='6')renderer.setView('bottom');else if(e.key==='0')renderer.setView('iso');else if(e.code==='Space'&&data?.fields.length){e.preventDefault();timeManager.toggle();}else if(e.key==='Escape'){if(pivotPicking)setPivotPicking(false);else if(pathPicking)setPathPicking(false);else setQueryMode('off');}});
updateLegend(0,1);updateTriad();viewCube.draw();renderWaypoints();
