import {KIND,EDGE_DEFS,SURFACE_VS,SURFACE_FS,PICK_FS,LINE_VS,LINE_FS,NODE_PICK_VS,NODE_PICK_FS,HILITE_VS,HILITE_FS,PLANE_VS,PLANE_FS} from './renderer-shaders.js?v=20260927e';
import {packXYZ,deriveNodal,stressIndices,program,uintTex,norm,quatFromBasis,quadPatch,triPatch} from './renderer-utils.js?v=20260927e';

export class RendererBase{
  constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext('webgl2',{antialias:true,alpha:false,preserveDrawingBuffer:true});if(!this.gl)throw new Error('WebGL 2 is required');this.data=null;this.batches={};this.patchCache=new Map();this.quality=6;this.fieldInfo={component:0,count:1,mode:0,stress:[0,1,2,3,4,5]};this.hasField=false;this.range={min:0,max:1,levels:18,continuous:false,palette:0,outside:true,below:[.541,.561,.58],above:[.541,.561,.58]};this.display={shape:true,deformed:false,deformScale:1,meshLines:true,boundary:true,undeformed:false};this.animationFactor=1;this.frameAlpha=0;this.nextDisplacementField=null;this.interpolationKey='';this.section={enabled:false,origin:[0,0,0],normal:[1,0,0],invert:false,showPlane:true};this.camera={target:[0,0,0],q:[0,0,0,1],distance:1,orthoScale:1,parallel:false,radius:1};this.gesture=null;this.onPivot=()=>{};this.onRender=()=>{};this.selectedNode=-1;this.selectedElement=-1;this.pathNodes=[];this._initGL();}
  _initGL(){const g=this.gl;g.enable(g.DEPTH_TEST);g.enable(g.CULL_FACE);g.cullFace(g.BACK);g.clearColor(.106,.122,.137,1);this.surfaceProgram=program(g,SURFACE_VS,SURFACE_FS);this.pickSurfaceProgram=program(g,SURFACE_VS,PICK_FS);this.lineProgram=program(g,LINE_VS,LINE_FS);this.nodePickProgram=program(g,NODE_PICK_VS,NODE_PICK_FS);this.hiliteProgram=program(g,HILITE_VS,HILITE_FS);this.planeProgram=program(g,PLANE_VS,PLANE_FS);this.dynamicLine=g.createBuffer();this.pathLine=g.createBuffer();this.planeBuffer=g.createBuffer();}
  load(data){this.disposeData();this.data=data;this.nodeCount=data.nodeIds.length;this.displacementField=null;this.hasField=false;this.fieldInfo={component:0,count:1,mode:0,stress:[0,1,2,3,4,5]};this.selectedNode=-1;this.selectedElement=-1;this.pathNodes=[];this.dynamicLineCount=0;this.pathLineCount=0;this._computeBounds();this.nodeTextureWidth=Math.min(2048,this.gl.getParameter(this.gl.MAX_TEXTURE_SIZE),Math.max(1,this.nodeCount));this.posTex=this._nodeTexture(packXYZ(data.positions,this.nodeCount));this.dispTex=this._nodeTexture(new Float32Array(this.nodeCount*4));this.nextDispTex=this._nodeTexture(new Float32Array(this.nodeCount*4));this.field0=this._nodeTexture(new Float32Array(this.nodeCount*4));this.field1=this._nodeTexture(new Float32Array(this.nodeCount*4));this.nextField0=this._nodeTexture(new Float32Array(this.nodeCount*4));this.nextField1=this._nodeTexture(new Float32Array(this.nodeCount*4));this.batches={};for(const [kind,b] of Object.entries(data.geometry.batches))if(b.count)this.batches[kind]=this._faceBatch(b);this.meshLineBuffer=this._indexBuffer(data.geometry.meshLines);this.boundaryBuffer=this._indexBuffer(data.geometry.boundaryLines);this.resultLineBuffer=this._indexBuffer(data.geometry.lineElements);this.fit();this._ensurePickFBO();this.render();}
  disposeData(){const g=this.gl;for(const t of ['posTex','dispTex','nextDispTex','field0','field1','nextField0','nextField1'])if(this[t])g.deleteTexture(this[t]);for(const b of Object.values(this.batches||{})){g.deleteTexture(b.conn0);g.deleteTexture(b.conn1);g.deleteTexture(b.elements);}for(const b of ['meshLineBuffer','boundaryBuffer','resultLineBuffer'])if(this[b])g.deleteBuffer(this[b]);this.batches={};}
  _computeBounds(){const p=this.data.positions;if(!p.length){this.bounds={min:[0,0,0],max:[1,1,1],center:[.5,.5,.5],radius:1};return;}const mn=[p[0],p[1],p[2]],mx=[...mn];for(let i=3;i<p.length;i+=3)for(let k=0;k<3;k++){mn[k]=Math.min(mn[k],p[i+k]);mx[k]=Math.max(mx[k],p[i+k]);}const c=mn.map((x,i)=>(x+mx[i])/2),r=Math.max(Math.hypot(mx[0]-mn[0],mx[1]-mn[1],mx[2]-mn[2])*.5,1e-12);this.bounds={min:mn,max:mx,center:c,radius:r};}
  displayBounds(){if(!this.data)return this.bounds;if(!this.display.deformed||!this.displacementField)return this.bounds;let mn=null,mx=null;for(let i=0;i<this.nodeCount;i++){const p=this._nodeWorld(i);if(!p.every(Number.isFinite))continue;if(!mn){mn=[...p];mx=[...p];continue;}for(let k=0;k<3;k++){mn[k]=Math.min(mn[k],p[k]);mx[k]=Math.max(mx[k],p[k]);}}if(!mn)return this.bounds;const center=mn.map((x,i)=>(x+mx[i])/2),radius=Math.max(Math.hypot(mx[0]-mn[0],mx[1]-mn[1],mx[2]-mn[2])*.5,1e-12);return{min:mn,max:mx,center,radius};}
  fit(){if(!this.data)return;const b=this.displayBounds();this.camera.target=[...b.center];this.camera.radius=b.radius;this.camera.distance=b.radius*3.0;this.camera.orthoScale=b.radius*1.2;this.render();}
  setView(name){const views={front:[0,-1,0],back:[0,1,0],right:[1,0,0],left:[-1,0,0],top:[0,0,1],bottom:[0,0,-1],iso:norm([1,-1,1])};this.setViewNormal(views[name]||views.iso);}
  setViewNormal(direction){const d=norm(direction),up=Math.abs(d[2])>.92?[0,1,0]:[0,0,1];this.camera.q=quatFromBasis(d,up);this.render();}
  setAnimationFactor(value){this.animationFactor=Math.max(-1,Math.min(1,Number.isFinite(value)?value:1));this.render();}
  toggleProjection(){const half=Math.PI/8;if(!this.camera.parallel){this.camera.orthoScale=Math.max(1e-12,this.camera.distance*Math.tan(half));this.camera.parallel=true;}else{this.camera.distance=Math.max(1e-12,this.camera.orthoScale/Math.tan(half));this.camera.parallel=false;}this.render();return this.camera.parallel;}
  setQuality(n){this.quality=Math.max(2,Math.min(16,n|0));this.render();}
  setDisplay(v){Object.assign(this.display,v);this.render();}
  setRange(v){Object.assign(this.range,v);this.render();}
  setSection(v){Object.assign(this.section,v);this.section.normal=norm(this.section.normal);this._updatePlane();this.render();}
  _packField(field,component,shape=true){const n=this.nodeCount,a=new Float32Array(n*4),b=new Float32Array(n*4);a.fill(NaN);b.fill(NaN);let info={component:0,count:1,mode:0,stress:[0,1,2,3,4,5]};if(field){const comps=field.components.map(x=>String(x).toUpperCase()),ci=field.components.indexOf(component);if(!shape&&(component==='Magnitude'||component==='Mises')){for(let i=0;i<n;i++){const row=[];for(let j=0;j<field.width;j++)row.push(field.values[i*field.width+j]);a[i*4]=deriveNodal(field.components,row,component);}info={component:0,count:1,mode:0,stress:[0,1,2,3,4,5]};}else{for(let i=0;i<n;i++)for(let j=0;j<Math.min(field.width,8);j++){const x=field.values[i*field.width+j];(j<4?a:b)[i*4+(j%4)]=x;}if(component==='Mises'){const idx=stressIndices(comps);info={component:0,count:field.width,mode:2,stress:idx};}else if(component==='Magnitude'){const all=comps.indexOf('ALL');if(all>=0)info={component:all,count:1,mode:3,stress:[0,1,2,3,4,5]};else info={component:0,count:Math.min(field.name.toUpperCase().startsWith('DISP')?3:field.width,8),mode:1,stress:[0,1,2,3,4,5]};}else info={component:Math.max(0,ci),count:field.width,mode:0,stress:[0,1,2,3,4,5]};}}return{a,b,info};}
  _packDisplacement(field){const a=new Float32Array(this.nodeCount*4);if(field){const c=field.components.map(x=>String(x).toUpperCase()),ix=[c.indexOf('D1'),c.indexOf('D2'),c.indexOf('D3')];for(let i=0;i<this.nodeCount;i++)for(let k=0;k<3;k++)if(ix[k]>=0)a[i*4+k]=field.values[i*field.width+ix[k]]||0;}return a;}
  setField(field,component,shape=true){if(!this.data)return;const packed=this._packField(field,component,shape);this.fieldInfo=packed.info;this.hasField=!!field;this._updateNodeTexture(this.field0,packed.a);this._updateNodeTexture(this.field1,packed.b);this._updateNodeTexture(this.nextField0,packed.a);this._updateNodeTexture(this.nextField1,packed.b);this.display.shape=shape;this.frameAlpha=0;this.interpolationKey='';this.render();}
  setDisplacement(field){this.displacementField=field||null;this.nextDisplacementField=null;const a=this._packDisplacement(field);this._updateNodeTexture(this.dispTex,a);this._updateNodeTexture(this.nextDispTex,a);this.frameAlpha=0;this.interpolationKey='';this.render();}
  setFrameInterpolation(field,displacement,component,shape,alpha){if(!this.data)return;const key=[field?.index??-1,displacement?.index??-1,component,shape?1:0].join(':');if(key!==this.interpolationKey){const packed=this._packField(field,component,shape);this._updateNodeTexture(this.nextField0,packed.a);this._updateNodeTexture(this.nextField1,packed.b);this._updateNodeTexture(this.nextDispTex,this._packDisplacement(displacement));this.nextDisplacementField=displacement||null;this.interpolationKey=key;}this.frameAlpha=Math.max(0,Math.min(1,Number.isFinite(alpha)?alpha:0));this.render();}
  clearFrameInterpolation(){this.frameAlpha=0;this.nextDisplacementField=null;this.interpolationKey='';this.render();}
  maxDisplacement(field){if(!field)return 0;const c=field.components.map(x=>String(x).toUpperCase()),ix=[c.indexOf('D1'),c.indexOf('D2'),c.indexOf('D3')];let m=0;for(let i=0;i<this.nodeCount;i++){const x=ix[0]>=0?field.values[i*field.width+ix[0]]:0,y=ix[1]>=0?field.values[i*field.width+ix[1]]:0,z=ix[2]>=0?field.values[i*field.width+ix[2]]:0;if(Number.isFinite(x)&&Number.isFinite(y)&&Number.isFinite(z))m=Math.max(m,Math.hypot(x,y,z));}return m;}
  autoDeformScale(field){const m=this.maxDisplacement(field);return m>1e-14?.1*(this.bounds.radius*2)/m:null;}
  scalarAtNode(field,component,i){if(!field||i<0)return NaN;const row=[];for(let j=0;j<field.width;j++)row.push(field.values[i*field.width+j]);return deriveNodal(field.components,row,component);}
  setSelection(node=-1,element=-1){this.selectedNode=node;this.selectedElement=element;this._updateSelectionLines();this.render();}
  setPath(nodes){this.pathNodes=nodes||[];const seg=[];for(let i=1;i<this.pathNodes.length;i++)seg.push(this.pathNodes[i-1],this.pathNodes[i]);const g=this.gl;g.bindBuffer(g.ARRAY_BUFFER,this.pathLine);g.bufferData(g.ARRAY_BUFFER,Uint32Array.from(seg),g.DYNAMIC_DRAW);this.pathLineCount=seg.length;this.render();}
  _updateSelectionLines(){const g=this.gl,seg=[];if(this.selectedElement>=0){const i=this.selectedElement,t=this.data.elementTypes[i],edges=EDGE_DEFS[t]||[],o=this.data.elementOffsets[i],c=this.data.elementConnectivity;for(const edge of edges){const seq=edge.map(k=>c[o+k]);for(let j=1;j<seq.length;j++)seg.push(seq[j-1],seq[j]);}}g.bindBuffer(g.ARRAY_BUFFER,this.dynamicLine);g.bufferData(g.ARRAY_BUFFER,Uint32Array.from(seg),g.DYNAMIC_DRAW);this.dynamicLineCount=seg.length;}
  _nodeTexture(rgba){const g=this.gl,w=this.nodeTextureWidth,h=Math.ceil(this.nodeCount/w),pad=new Float32Array(w*h*4);pad.fill(NaN);pad.set(rgba);const t=g.createTexture();g.bindTexture(g.TEXTURE_2D,t);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.NEAREST);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.NEAREST);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE);g.texImage2D(g.TEXTURE_2D,0,g.RGBA32F,w,h,0,g.RGBA,g.FLOAT,pad);return t;}
  _updateNodeTexture(t,rgba){const g=this.gl,w=this.nodeTextureWidth,h=Math.ceil(this.nodeCount/w),pad=new Float32Array(w*h*4);pad.fill(NaN);pad.set(rgba);g.bindTexture(g.TEXTURE_2D,t);g.texSubImage2D(g.TEXTURE_2D,0,0,0,w,h,g.RGBA,g.FLOAT,pad);}
  _faceBatch(b){const g=this.gl,w=Math.min(2048,g.getParameter(g.MAX_TEXTURE_SIZE),Math.max(1,b.count)),h=Math.ceil(b.count/w),a=new Uint32Array(w*h*4),z=new Uint32Array(w*h*4);a.fill(0xffffffff);z.fill(0xffffffff);for(let i=0;i<b.count;i++){a.set(b.nodes.subarray(i*8,i*8+4),i*4);z.set(b.nodes.subarray(i*8+4,i*8+8),i*4);}const conn0=uintTex(g,a,w,h,g.RGBA32UI,g.RGBA_INTEGER),conn1=uintTex(g,z,w,h,g.RGBA32UI,g.RGBA_INTEGER),el=new Uint32Array(w*h);el.fill(0xffffffff);el.set(b.elements);const elements=uintTex(g,el,w,h,g.R32UI,g.RED_INTEGER);return{count:b.count,width:w,conn0,conn1,elements};}
  _indexBuffer(a){const g=this.gl,b=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,b);g.bufferData(g.ARRAY_BUFFER,a,g.STATIC_DRAW);b.count=a.length;return b;}
  _patch(kind,shape){const tri=kind[0]==='t',res=shape?this.quality:1,key=`${tri?'t':'q'}:${res}`;if(this.patchCache.has(key))return this.patchCache.get(key);const uv=tri?triPatch(res):quadPatch(res),g=this.gl,b=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,b);g.bufferData(g.ARRAY_BUFFER,uv,g.STATIC_DRAW);const out={buffer:b,count:uv.length/2};this.patchCache.set(key,out);return out;}
}
