function packXYZ(p,n){const a=new Float32Array(n*4);for(let i=0;i<n;i++){a[i*4]=p[i*3];a[i*4+1]=p[i*3+1];a[i*4+2]=p[i*3+2];a[i*4+3]=1;}return a;}
function deriveNodal(components,row,component){if(component==='Magnitude'){const u=components.map(x=>String(x).toUpperCase()),all=u.indexOf('ALL');if(all>=0)return row[all];const count=Math.max(1,row.length);let s=0;for(let i=0;i<count;i++)s+=(row[i]||0)**2;return Math.sqrt(s);}if(component==='Mises'){const u=components.map(x=>String(x).toUpperCase()),ix=stressIndices(u);if(ix.some(i=>i<0))return NaN;const [sxx,syy,szz,sxy,syz,szx]=ix.map(i=>row[i]);return Math.sqrt(Math.max(.5*((sxx-syy)**2+(syy-szz)**2+(szz-sxx)**2)+3*(sxy*sxy+syz*syz+szx*szx),0));}const i=components.indexOf(component);return i>=0?row[i]:NaN;}
function stressIndices(u){return[u.indexOf('SXX'),u.indexOf('SYY'),u.indexOf('SZZ'),u.indexOf('SXY'),u.indexOf('SYZ'),Math.max(u.indexOf('SZX'),u.indexOf('SXZ'))];}
function quadPatch(n){const a=[];for(let j=0;j<n;j++)for(let i=0;i<n;i++){const x0=-1+2*i/n,x1=-1+2*(i+1)/n,y0=-1+2*j/n,y1=-1+2*(j+1)/n;a.push(x0,y0,x1,y0,x1,y1,x0,y0,x1,y1,x0,y1);}return new Float32Array(a);}
function triPatch(n){const a=[];for(let j=0;j<n;j++)for(let i=0;i<n-j;i++){const A=[i/n,j/n],B=[(i+1)/n,j/n],C=[i/n,(j+1)/n],D=[(i+1)/n,(j+1)/n];a.push(...A,...B,...C);if(i+j<n-1)a.push(...B,...D,...C);}return new Float32Array(a);}
function shader(g,t,s){const x=g.createShader(t);g.shaderSource(x,s);g.compileShader(x);if(!g.getShaderParameter(x,g.COMPILE_STATUS))throw new Error(g.getShaderInfoLog(x));return x;}function program(g,v,f){const p=g.createProgram();g.attachShader(p,shader(g,g.VERTEX_SHADER,v));g.attachShader(p,shader(g,g.FRAGMENT_SHADER,f));g.linkProgram(p);if(!g.getProgramParameter(p,g.LINK_STATUS))throw new Error(g.getProgramInfoLog(p));return p;}
function uintTex(g,a,w,h,internal,format){const t=g.createTexture();g.bindTexture(g.TEXTURE_2D,t);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.NEAREST);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.NEAREST);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE);g.texImage2D(g.TEXTURE_2D,0,internal,w,h,0,format,g.UNSIGNED_INT,a);return t;}
function loc(g,p,n){return g.getUniformLocation(p,n);}function bindTex(g,p,n,t,u){g.activeTexture(g.TEXTURE0+u);g.bindTexture(g.TEXTURE_2D,t);g.uniform1i(loc(g,p,n),u);}function ui(g,p,n,v){g.uniform1i(loc(g,p,n),v);}function ub(g,p,n,v){g.uniform1i(loc(g,p,n),v?1:0);}function uf(g,p,n,v){g.uniform1f(loc(g,p,n),v);}function u4(g,p,n,v){g.uniform4fv(loc(g,p,n),v);}function u3(g,p,n,v){g.uniform3fv(loc(g,p,n),v);}function uiv(g,p,n,v){g.uniform4iv(loc(g,p,n),v);}function uiv2(g,p,n,v){g.uniform2iv(loc(g,p,n),v);}function um4(g,p,n,v){g.uniformMatrix4fv(loc(g,p,n),false,v);}function rangeUniforms(g,p,r){uf(g,p,'uMin',r.min);uf(g,p,'uMax',r.max);ui(g,p,'uLevels',r.levels);ui(g,p,'uPalette',r.palette);ub(g,p,'uContinuous',r.continuous);ub(g,p,'uOutside',r.outside);u3(g,p,'uBelow',r.below);u3(g,p,'uAbove',r.above);}function clipUniforms(g,p,s){ub(g,p,'uClipEnabled',s.enabled);u3(g,p,'uClipOrigin',s.origin);u3(g,p,'uClipNormal',norm(s.normal));uf(g,p,'uClipSign',s.invert?-1:1);}
function add(a,b){return[a[0]+b[0],a[1]+b[1],a[2]+b[2]];}function sub(a,b){return[a[0]-b[0],a[1]-b[1],a[2]-b[2]];}function mulv(a,s){return[a[0]*s,a[1]*s,a[2]*s];}function dot(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2];}function cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];}function norm(a){const l=Math.hypot(...a)||1;return a.map(x=>x/l);}
function qmul(a,b){return[a[3]*b[0]+a[0]*b[3]+a[1]*b[2]-a[2]*b[1],a[3]*b[1]-a[0]*b[2]+a[1]*b[3]+a[2]*b[0],a[3]*b[2]+a[0]*b[1]-a[1]*b[0]+a[2]*b[3],a[3]*b[3]-a[0]*b[0]-a[1]*b[1]-a[2]*b[2]];}function qconj(q){return[-q[0],-q[1],-q[2],q[3]];}function qnorm(q){const l=Math.hypot(...q)||1;return q.map(x=>x/l);}function qrot(q,v){const p=[v[0],v[1],v[2],0],r=qmul(qmul(q,p),qconj(q));return[r[0],r[1],r[2]];}function qFromTo(a,b){const c=cross(a,b),d=dot(a,b);if(d<-0.999999){const axis=norm(Math.abs(a[0])<.9?cross(a,[1,0,0]):cross(a,[0,1,0]));return[axis[0],axis[1],axis[2],0];}return qnorm([c[0],c[1],c[2],1+d]);}
function quatFromBasis(eyeDir,upHint){const z=norm(eyeDir),x=norm(cross(upHint,z)),y=cross(z,x),m=[x[0],y[0],z[0],x[1],y[1],z[1],x[2],y[2],z[2]],tr=m[0]+m[4]+m[8];let q;if(tr>0){const s=Math.sqrt(tr+1)*2;q=[(m[7]-m[5])/s,(m[2]-m[6])/s,(m[3]-m[1])/s,.25*s];}else if(m[0]>m[4]&&m[0]>m[8]){const s=Math.sqrt(1+m[0]-m[4]-m[8])*2;q=[.25*s,(m[1]+m[3])/s,(m[2]+m[6])/s,(m[7]-m[5])/s];}else if(m[4]>m[8]){const s=Math.sqrt(1+m[4]-m[0]-m[8])*2;q=[(m[1]+m[3])/s,.25*s,(m[5]+m[7])/s,(m[2]-m[6])/s];}else{const s=Math.sqrt(1+m[8]-m[0]-m[4])*2;q=[(m[2]+m[6])/s,(m[5]+m[7])/s,.25*s,(m[3]-m[1])/s];}return qnorm(q);}
function lookAt(e,c,u){const z=norm(sub(e,c)),x=norm(cross(u,z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,e),-dot(y,e),-dot(z,e),1]);}function perspective(f,a,n,fa){const q=1/Math.tan(f/2);return new Float32Array([q/a,0,0,0,0,q,0,0,0,0,(fa+n)/(n-fa),-1,0,0,2*fa*n/(n-fa),0]);}function ortho(l,r,b,t,n,f){return new Float32Array([2/(r-l),0,0,0,0,2/(t-b),0,0,0,0,-2/(f-n),0,-(r+l)/(r-l),-(t+b)/(t-b),-(f+n)/(f-n),1]);}function mm(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o;}function transform4(m,v){return[m[0]*v[0]+m[4]*v[1]+m[8]*v[2]+m[12]*v[3],m[1]*v[0]+m[5]*v[1]+m[9]*v[2]+m[13]*v[3],m[2]*v[0]+m[6]*v[1]+m[10]*v[2]+m[14]*v[3],m[3]*v[0]+m[7]*v[1]+m[11]*v[2]+m[15]*v[3]];}

export {packXYZ,deriveNodal,stressIndices,quadPatch,triPatch,program,uintTex,bindTex,ui,ub,uf,u4,u3,uiv,uiv2,um4,rangeUniforms,clipUniforms,add,sub,mulv,dot,cross,norm,qmul,qconj,qnorm,qrot,qFromTo,quatFromBasis,lookAt,perspective,ortho,mm,transform4};
