import {KIND,EDGE_DEFS} from './renderer-shaders.js?v=20260927i';
import {RendererBase} from './renderer-base.js?v=20260927i';
import {bindTex,ui,ub,uf,u4,u3,uiv,uiv2,um4,rangeUniforms,clipUniforms,add,sub,mulv,dot,cross,norm,qmul,qconj,qnorm,qrot,qFromTo,lookAt,perspective,ortho,mm,transform4} from './renderer-utils.js?v=20260927i';

export class Renderer extends RendererBase {
  resize(){const d=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.floor(this.canvas.clientWidth*d)),h=Math.max(1,Math.floor(this.canvas.clientHeight*d));if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;this.gl.viewport(0,0,w,h);this._ensurePickFBO();}return[w,h];}
  vp(){const [w,h]=this.resize(),aspect=w/h,c=this.camera,eyeDir=qrot(c.q,[0,0,1]),up=qrot(c.q,[0,1,0]),eye=add(c.target,mulv(eyeDir,c.distance)),V=lookAt(eye,c.target,up);let P;if(c.parallel)P=ortho(-c.orthoScale*aspect,c.orthoScale*aspect,-c.orthoScale,c.orthoScale,-c.radius*8,c.radius*8);else{const near=Math.max(c.radius*1e-4,c.distance-c.radius*2.2,.000001),far=Math.max(near*10,c.distance+c.radius*3);P=perspective(Math.PI/4,aspect,near,far);}return mm(P,V);}
  render(){const g=this.gl;this.resize();g.bindFramebuffer(g.FRAMEBUFFER,null);g.viewport(0,0,this.canvas.width,this.canvas.height);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);if(!this.data)return;const vp=this.vp();if(this.display.undeformed&&this.meshLineBuffer)this._drawLines(this.meshLineBuffer,false,[.58,.63,.67,.72],vp,false,1.0e-4);this._drawSurfaces(vp,false);if(this.resultLineBuffer?.count)this._drawLines(this.resultLineBuffer,this.hasField,[1,1,1,1],vp,true,1.5e-4);if(this.display.meshLines&&this.meshLineBuffer)this._drawLines(this.meshLineBuffer,false,[.10,.12,.14,.72],vp,true,1.8e-4);if(this.display.boundary&&this.boundaryBuffer)this._drawLines(this.boundaryBuffer,false,[.88,.90,.92,.92],vp,true,2.4e-4);if(this.section.enabled&&this.sectionCapCount)this._drawSectionCap(vp);if(this.section.enabled&&this.section.showPlane)this._drawPlane(vp);if(this.dynamicLineCount)this._drawHighlightLines(this.dynamicLine,this.dynamicLineCount,[1,.86,.25,1],vp);if(this.pathLineCount)this._drawHighlightLines(this.pathLine,this.pathLineCount,[.20,.82,1,1],vp);if(this.pathNodeCount)this._drawNodePoints(this.pathNodeBuffer,this.pathNodeCount,[.20,.82,1,1],5,vp);if(this.pathWaypointCount)this._drawNodePoints(this.pathWaypointBuffer,this.pathWaypointCount,[1,.72,.20,1],14,vp);if(this.selectedNode>=0)this._drawSelectedNode(vp);this.onRender();}
  _commonSurface(p,vp,b,kind){const g=this.gl;g.useProgram(p);bindTex(g,p,'uPosTex',this.posTex,0);bindTex(g,p,'uField0',this.field0,1);bindTex(g,p,'uField1',this.field1,2);bindTex(g,p,'uDispTex',this.dispTex,3);bindTex(g,p,'uConn0',b.conn0,4);bindTex(g,p,'uConn1',b.conn1,5);bindTex(g,p,'uElementTex',b.elements,6);bindTex(g,p,'uNextField0',this.nextField0,7);bindTex(g,p,'uNextField1',this.nextField1,8);bindTex(g,p,'uNextDispTex',this.nextDispTex,9);ui(g,p,'uNodeTexWidth',this.nodeTextureWidth);ui(g,p,'uFaceTexWidth',b.width);ui(g,p,'uKind',KIND[kind]);ub(g,p,'uHighOrder',this.display.shape);ub(g,p,'uDeformed',this.display.deformed);uf(g,p,'uDeformScale',this.display.deformScale);uf(g,p,'uAnimFactor',this.animationFactor);uf(g,p,'uFrameAlpha',this.frameAlpha);um4(g,p,'uVP',vp);ui(g,p,'uComponent',this.fieldInfo.component);ui(g,p,'uComponentCount',this.fieldInfo.count);ui(g,p,'uScalarMode',this.fieldInfo.mode);uiv(g,p,'uStress0',this.fieldInfo.stress.slice(0,4));uiv2(g,p,'uStress1',this.fieldInfo.stress.slice(4,6));clipUniforms(g,p,this.section);ub(g,p,'uHasField',this.hasField);}
  _drawSurfaces(vp,picking){const g=this.gl,p=picking?this.pickSurfaceProgram:this.surfaceProgram;g.disable(g.CULL_FACE);for(const [kind,b] of Object.entries(this.batches)){const patch=this._patch(kind,this.display.shape);this._commonSurface(p,vp,b,kind);if(!picking)rangeUniforms(g,p,this.range);g.bindBuffer(g.ARRAY_BUFFER,patch.buffer);g.enableVertexAttribArray(0);g.vertexAttribPointer(0,2,g.FLOAT,false,0,0);g.drawArraysInstanced(g.TRIANGLES,0,patch.count,b.count);}g.enable(g.CULL_FACE);}
  _drawLines(buffer,useScalar,color,vp,deformed=true,depthBias=0){const g=this.gl,p=this.lineProgram;g.useProgram(p);bindTex(g,p,'uPosTex',this.posTex,0);bindTex(g,p,'uDispTex',this.dispTex,1);bindTex(g,p,'uField0',this.field0,2);bindTex(g,p,'uField1',this.field1,3);bindTex(g,p,'uNextDispTex',this.nextDispTex,4);bindTex(g,p,'uNextField0',this.nextField0,5);bindTex(g,p,'uNextField1',this.nextField1,6);ui(g,p,'uNodeTexWidth',this.nodeTextureWidth);ub(g,p,'uDeformed',deformed&&this.display.deformed);uf(g,p,'uDeformScale',this.display.deformScale);uf(g,p,'uAnimFactor',this.animationFactor);uf(g,p,'uFrameAlpha',this.frameAlpha);uf(g,p,'uDepthBias',depthBias);um4(g,p,'uVP',vp);ui(g,p,'uComponent',this.fieldInfo.component);ui(g,p,'uComponentCount',this.fieldInfo.count);ui(g,p,'uScalarMode',this.fieldInfo.mode);uiv(g,p,'uStress0',this.fieldInfo.stress.slice(0,4));uiv2(g,p,'uStress1',this.fieldInfo.stress.slice(4,6));ub(g,p,'uUseScalar',useScalar);u4(g,p,'uColor',color);rangeUniforms(g,p,this.range);clipUniforms(g,p,this.section);g.bindBuffer(g.ARRAY_BUFFER,buffer);g.enableVertexAttribArray(0);g.vertexAttribIPointer(0,1,g.UNSIGNED_INT,0,0);g.depthFunc(g.LEQUAL);g.drawArrays(g.LINES,0,buffer.count);g.depthFunc(g.LESS);}
  _drawHighlightLines(buffer,count,color,vp){const g=this.gl,p=this.hiliteProgram;g.useProgram(p);bindTex(g,p,'uPosTex',this.posTex,0);bindTex(g,p,'uDispTex',this.dispTex,1);bindTex(g,p,'uNextDispTex',this.nextDispTex,2);ui(g,p,'uNodeTexWidth',this.nodeTextureWidth);ub(g,p,'uDeformed',this.display.deformed);uf(g,p,'uDeformScale',this.display.deformScale);uf(g,p,'uAnimFactor',this.animationFactor);uf(g,p,'uFrameAlpha',this.frameAlpha);um4(g,p,'uVP',vp);u4(g,p,'uColor',color);ub(g,p,'uPoint',false);uf(g,p,'uPointSize',1);uf(g,p,'uDepthBias',3.0e-4);g.bindBuffer(g.ARRAY_BUFFER,buffer);g.enableVertexAttribArray(0);g.vertexAttribIPointer(0,1,g.UNSIGNED_INT,0,0);g.drawArrays(g.LINES,0,count);}
  _drawSelectedNode(vp){const g=this.gl,p=this.hiliteProgram,b=this.dynamicNode||(this.dynamicNode=g.createBuffer());g.bindBuffer(g.ARRAY_BUFFER,b);g.bufferData(g.ARRAY_BUFFER,new Uint32Array([this.selectedNode]),g.DYNAMIC_DRAW);g.useProgram(p);bindTex(g,p,'uPosTex',this.posTex,0);bindTex(g,p,'uDispTex',this.dispTex,1);bindTex(g,p,'uNextDispTex',this.nextDispTex,2);ui(g,p,'uNodeTexWidth',this.nodeTextureWidth);ub(g,p,'uDeformed',this.display.deformed);uf(g,p,'uDeformScale',this.display.deformScale);uf(g,p,'uAnimFactor',this.animationFactor);uf(g,p,'uFrameAlpha',this.frameAlpha);um4(g,p,'uVP',vp);u4(g,p,'uColor',[1,.86,.25,1]);ub(g,p,'uPoint',true);uf(g,p,'uPointSize',13);uf(g,p,'uDepthBias',3.5e-4);g.enable(g.BLEND);g.blendFunc(g.SRC_ALPHA,g.ONE_MINUS_SRC_ALPHA);g.enableVertexAttribArray(0);g.vertexAttribIPointer(0,1,g.UNSIGNED_INT,0,0);g.drawArrays(g.POINTS,0,1);g.disable(g.BLEND);}
  _drawNodePoints(buffer,count,color,size,vp){if(!count)return;const g=this.gl,p=this.hiliteProgram;g.useProgram(p);bindTex(g,p,'uPosTex',this.posTex,0);bindTex(g,p,'uDispTex',this.dispTex,1);bindTex(g,p,'uNextDispTex',this.nextDispTex,2);ui(g,p,'uNodeTexWidth',this.nodeTextureWidth);ub(g,p,'uDeformed',this.display.deformed);uf(g,p,'uDeformScale',this.display.deformScale);uf(g,p,'uAnimFactor',this.animationFactor);uf(g,p,'uFrameAlpha',this.frameAlpha);um4(g,p,'uVP',vp);u4(g,p,'uColor',color);ub(g,p,'uPoint',true);uf(g,p,'uPointSize',size);uf(g,p,'uDepthBias',3.5e-4);g.bindBuffer(g.ARRAY_BUFFER,buffer);g.enableVertexAttribArray(0);g.vertexAttribIPointer(0,1,g.UNSIGNED_INT,0,0);g.depthFunc(g.LEQUAL);g.drawArrays(g.POINTS,0,count);g.depthFunc(g.LESS);}
  _updateSectionCap(){const g=this.gl;if(!this.data||!this.section.enabled){this.sectionCapCount=0;return;}const n=norm(this.section.normal),o=this.section.origin,eps=Math.max(this.bounds.radius*1e-8,1e-10),eps2=eps*eps*16,verts=[],types=this.data.elementTypes,offs=this.data.elementOffsets,conn=this.data.elementConnectivity;
    const pushUnique=(arr,p)=>{for(const q of arr){const dx=q[0]-p[0],dy=q[1]-p[1],dz=q[2]-p[2];if(dx*dx+dy*dy+dz*dz<=eps2)return;}arr.push(p);};
    for(let ei=0;ei<types.length;ei++){const type=types[ei];if(type<1||type>6)continue;const edges=EDGE_DEFS[type]||[],base=offs[ei],pts=[];
      for(const edge of edges){for(let j=1;j<edge.length;j++){const ia=conn[base+edge[j-1]],ib=conn[base+edge[j]],a=this._nodeWorld(ia),b=this._nodeWorld(ib),da=dot(sub(a,o),n),db=dot(sub(b,o),n);if(Math.abs(da)<=eps)pushUnique(pts,a);if(Math.abs(db)<=eps)pushUnique(pts,b);if((da< -eps&&db>eps)||(da>eps&&db< -eps)){const t=da/(da-db);pushUnique(pts,[a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t,a[2]+(b[2]-a[2])*t]);}}}
      if(pts.length<3)continue;const c=[0,0,0];for(const p of pts){c[0]+=p[0];c[1]+=p[1];c[2]+=p[2];}c[0]/=pts.length;c[1]/=pts.length;c[2]/=pts.length;const ref=Math.abs(n[0])<.85?[1,0,0]:[0,1,0],u=norm(cross(n,ref)),v=cross(n,u);pts.sort((a,b)=>Math.atan2(dot(sub(a,c),v),dot(sub(a,c),u))-Math.atan2(dot(sub(b,c),v),dot(sub(b,c),u)));for(let i=0;i<pts.length;i++){const a=pts[i],b=pts[(i+1)%pts.length];verts.push(...c,...a,...b);}}
    const arr=new Float32Array(verts);g.bindBuffer(g.ARRAY_BUFFER,this.sectionCapBuffer);g.bufferData(g.ARRAY_BUFFER,arr,g.DYNAMIC_DRAW);this.sectionCapCount=arr.length/3;}
  _drawSectionCap(vp){if(!this.sectionCapCount)return;const g=this.gl,p=this.capProgram;g.useProgram(p);um4(g,p,'uVP',vp);g.bindBuffer(g.ARRAY_BUFFER,this.sectionCapBuffer);g.enableVertexAttribArray(0);g.vertexAttribPointer(0,3,g.FLOAT,false,0,0);g.disable(g.CULL_FACE);g.depthFunc(g.LEQUAL);g.drawArrays(g.TRIANGLES,0,this.sectionCapCount);g.depthFunc(g.LESS);g.enable(g.CULL_FACE);}
  _updatePlane(){if(!this.data)return;const n=norm(this.section.normal),ref=Math.abs(n[1])<.9?[0,1,0]:[1,0,0],u=norm(cross(n,ref)),v=cross(n,u),r=this.bounds.radius*1.45,o=this.section.origin,pts=[add(add(o,mulv(u,-r)),mulv(v,-r)),add(add(o,mulv(u,r)),mulv(v,-r)),add(add(o,mulv(u,r)),mulv(v,r)),add(add(o,mulv(u,-r)),mulv(v,-r)),add(add(o,mulv(u,r)),mulv(v,r)),add(add(o,mulv(u,-r)),mulv(v,r))];const a=new Float32Array(18);pts.forEach((p,i)=>a.set(p,i*3));const g=this.gl;g.bindBuffer(g.ARRAY_BUFFER,this.planeBuffer);g.bufferData(g.ARRAY_BUFFER,a,g.DYNAMIC_DRAW);}
  _drawPlane(vp){const g=this.gl,p=this.planeProgram;g.useProgram(p);um4(g,p,'uVP',vp);g.bindBuffer(g.ARRAY_BUFFER,this.planeBuffer);g.enableVertexAttribArray(0);g.vertexAttribPointer(0,3,g.FLOAT,false,0,0);g.enable(g.BLEND);g.blendFunc(g.SRC_ALPHA,g.ONE_MINUS_SRC_ALPHA);g.depthMask(false);g.disable(g.CULL_FACE);g.drawArrays(g.TRIANGLES,0,6);g.enable(g.CULL_FACE);g.depthMask(true);g.disable(g.BLEND);}
  _ensurePickFBO(){const g=this.gl,w=this.canvas.width||1,h=this.canvas.height||1;if(this.pickSize?.[0]===w&&this.pickSize?.[1]===h)return;if(this.pickFBO){g.deleteFramebuffer(this.pickFBO);g.deleteTexture(this.pickColor);g.deleteRenderbuffer(this.pickDepth);}this.pickFBO=g.createFramebuffer();g.bindFramebuffer(g.FRAMEBUFFER,this.pickFBO);this.pickColor=g.createTexture();g.bindTexture(g.TEXTURE_2D,this.pickColor);g.texImage2D(g.TEXTURE_2D,0,g.RGBA8,w,h,0,g.RGBA,g.UNSIGNED_BYTE,null);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.NEAREST);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.NEAREST);g.framebufferTexture2D(g.FRAMEBUFFER,g.COLOR_ATTACHMENT0,g.TEXTURE_2D,this.pickColor,0);this.pickDepth=g.createRenderbuffer();g.bindRenderbuffer(g.RENDERBUFFER,this.pickDepth);g.renderbufferStorage(g.RENDERBUFFER,g.DEPTH_COMPONENT24,w,h);g.framebufferRenderbuffer(g.FRAMEBUFFER,g.DEPTH_ATTACHMENT,g.RENDERBUFFER,this.pickDepth);g.bindFramebuffer(g.FRAMEBUFFER,null);this.pickSize=[w,h];}
  pick(mode,clientX,clientY){if(!this.data)return-1;const g=this.gl;this.resize();this._ensurePickFBO();g.bindFramebuffer(g.FRAMEBUFFER,this.pickFBO);g.viewport(0,0,this.canvas.width,this.canvas.height);g.clearColor(0,0,0,0);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);const vp=this.vp();if(mode==='element')this._drawSurfaces(vp,true);else if(mode==='node'){g.colorMask(false,false,false,false);this._drawSurfaces(vp,true);g.colorMask(true,true,true,true);const p=this.nodePickProgram;g.useProgram(p);bindTex(g,p,'uPosTex',this.posTex,0);bindTex(g,p,'uDispTex',this.dispTex,1);bindTex(g,p,'uNextDispTex',this.nextDispTex,2);ui(g,p,'uNodeTexWidth',this.nodeTextureWidth);ub(g,p,'uDeformed',this.display.deformed);uf(g,p,'uDeformScale',this.display.deformScale);uf(g,p,'uAnimFactor',this.animationFactor);uf(g,p,'uFrameAlpha',this.frameAlpha);um4(g,p,'uVP',vp);clipUniforms(g,p,this.section);g.depthFunc(g.LEQUAL);g.drawArrays(g.POINTS,0,this.nodeCount);g.depthFunc(g.LESS);}const rect=this.canvas.getBoundingClientRect(),x=Math.floor((clientX-rect.left)*this.canvas.width/rect.width),y=Math.floor((rect.bottom-clientY)*this.canvas.height/rect.height),px=new Uint8Array(4);g.readPixels(Math.max(0,Math.min(this.canvas.width-1,x)),Math.max(0,Math.min(this.canvas.height-1,y)),1,1,g.RGBA,g.UNSIGNED_BYTE,px);g.bindFramebuffer(g.FRAMEBUFFER,null);g.clearColor(.106,.122,.137,1);this.render();const id=px[0]+(px[1]<<8)+(px[2]<<16);if(id)return id-1;return mode==='element'?this._pickLineElement(clientX,clientY):-1;}

  _nodeWorld(i){const p=[this.data.positions[i*3],this.data.positions[i*3+1],this.data.positions[i*3+2]];if(!this.display.deformed||!this.displacementField)return p;const f=this.displacementField,c=f.components.map(x=>String(x).toUpperCase()),ix=['D1','D2','D3'].map(x=>c.indexOf(x)),nf=this.nextDisplacementField,nc=nf?nf.components.map(x=>String(x).toUpperCase()):null,nix=nc?['D1','D2','D3'].map(x=>nc.indexOf(x)):ix;for(let k=0;k<3;k++){const v=ix[k]>=0?f.values[i*f.width+ix[k]]:0,nv=nf&&nix[k]>=0?nf.values[i*nf.width+nix[k]]:v,dv=Number.isFinite(v)&&Number.isFinite(nv)?v+(nv-v)*this.frameAlpha:v;if(Number.isFinite(dv))p[k]+=this.display.deformScale*this.animationFactor*dv;}return p;}
  _pickLineElement(clientX,clientY){const seg=this.data?.geometry?.lineElements,owners=this.data?.geometry?.lineElementIds;if(!seg?.length||!owners?.length)return-1;const rect=this.canvas.getBoundingClientRect(),px=clientX-rect.left,py=clientY-rect.top,vp=this.vp();let best=-1,bestD=8,bestZ=Infinity;const clip=this.section.enabled?{o:this.section.origin,n:norm(this.section.normal),s:this.section.invert?-1:1}:null;for(let si=0;si<owners.length;si++){let a=this._nodeWorld(seg[si*2]),b=this._nodeWorld(seg[si*2+1]);if(clip){let da=clip.s*dot(sub(a,clip.o),clip.n),db=clip.s*dot(sub(b,clip.o),clip.n);if(da<0&&db<0)continue;if((da<0)!=(db<0)){const t=da/(da-db),p=add(a,mulv(sub(b,a),t));if(da<0)a=p;else b=p;}}const A=transform4(vp,[...a,1]),B=transform4(vp,[...b,1]);if(A[3]<=0||B[3]<=0)continue;const ax=(A[0]/A[3]*.5+.5)*rect.width,ay=(1-(A[1]/A[3]*.5+.5))*rect.height,bx=(B[0]/B[3]*.5+.5)*rect.width,by=(1-(B[1]/B[3]*.5+.5))*rect.height,dx=bx-ax,dy=by-ay,l2=dx*dx+dy*dy,t=l2?Math.max(0,Math.min(1,((px-ax)*dx+(py-ay)*dy)/l2)):0,x=ax+t*dx,y=ay+t*dy,d=Math.hypot(px-x,py-y),z=(A[2]/A[3])*(1-t)+(B[2]/B[3])*t;if(d<bestD-1e-6||(Math.abs(d-bestD)<1e-6&&z<bestZ)){bestD=d;bestZ=z;best=owners[si];}}return best;}
  pointerDown(e){if(!this.data)return;this.cancelViewAnimation();const rect=this.canvas.getBoundingClientRect(),p=[e.clientX-rect.left,e.clientY-rect.top],button=e.button;this.gesture={button,start:p,last:p,dragging:false,q:[...this.camera.q],arc:this._arc(p)};}
  pointerMove(e){const s=this.gesture;if(!s)return false;const rect=this.canvas.getBoundingClientRect(),p=[e.clientX-rect.left,e.clientY-rect.top],dx=p[0]-s.last[0],dy=p[1]-s.last[1];s.last=p;if(!s.dragging&&Math.hypot(p[0]-s.start[0],p[1]-s.start[1])>3){s.dragging=true;if(s.button===0)this.onPivot(true,this.projectPivot());}if(!s.dragging)return false;if(s.button===0){const cur=this._arc(p),dq=qFromTo(s.arc,cur);this.camera.q=qnorm(qmul(s.q,qconj(dq)));}else if(s.button===1||s.button===2){const scale=this.camera.parallel?2*this.camera.orthoScale/Math.max(1,this.canvas.clientHeight):2*this.camera.distance*Math.tan(Math.PI/8)/Math.max(1,this.canvas.clientHeight),right=qrot(this.camera.q,[1,0,0]),up=qrot(this.camera.q,[0,1,0]);this.camera.target=add(this.camera.target,add(mulv(right,-dx*scale),mulv(up,dy*scale)));}this.render();return true;}
  pointerUp(){const s=this.gesture;if(!s)return false;this.gesture=null;if(s.dragging&&s.button===0)this.onPivot(false,this.projectPivot());return!s.dragging&&s.button===0;}
  wheel(e){this.cancelViewAnimation();const f=Math.exp(e.deltaY*.001);if(this.camera.parallel)this.camera.orthoScale=Math.max(this.bounds.radius*1e-5,Math.min(this.bounds.radius*1e4,this.camera.orthoScale*f));else this.camera.distance=Math.max(this.bounds.radius*.02,Math.min(this.bounds.radius*1e4,this.camera.distance*f));this.render();}
  _arc(p){const w=Math.max(1,this.canvas.clientWidth),h=Math.max(1,this.canvas.clientHeight),x=(2*p[0]-w)/Math.min(w,h),y=(h-2*p[1])/Math.min(w,h),d=x*x+y*y,z=d<=.5?Math.sqrt(1-d):.5/Math.sqrt(d);return norm([x,y,z]);}
  projectPivot(){const vp=this.vp(),p=transform4(vp,[...this.camera.target,1]);if(!p[3])return[.5,.5];const x=p[0]/p[3],y=p[1]/p[3];return[(x*.5+.5)*this.canvas.clientWidth,(1-(y*.5+.5))*this.canvas.clientHeight];}
  _updateNodeSelectionPosition(){}
  cameraBasis(){return{right:qrot(this.camera.q,[1,0,0]),up:qrot(this.camera.q,[0,1,0]),eye:qrot(this.camera.q,[0,0,1])};}
  screenshot(){this.render();return this.canvas.toDataURL('image/png');}
}
