"""Central pixel metrics for high-level OpenCAE desktop layout."""

RIBBON_ICON_SIZE = 42
RIBBON_BUTTON_WIDTH = 78
RIBBON_BUTTON_HEIGHT = 80
RIBBON_PAGE_HEIGHT = 104
STAGE_BAR_HEIGHT = 43
TREE_ROW_HEIGHT = 26
DOCK_MIN_WIDTH = 280
OUTPUT_MIN_HEIGHT = 190
