"""Contour semantics layered on top of the generic Time Manager playback panel."""

from __future__ import annotations

from .time_manager import TimeManagerPanel, current_frame_amplitude, frame_bracket


_UNSIGNED_COMPONENTS = {
    "magnitude",
    "mises",
    "von mises",
    "von_mises",
    "equivalent",
    "tresca",
}


def is_unsigned_component(field) -> bool:
    """Return whether the displayed scalar is an invariant/magnitude without sign."""
    if field is None:
        return False
    component = str(
        field.metadata.get(
            "component",
            field.metadata.get("default_component", "Magnitude"),
        )
    ).strip().casefold()
    return component in _UNSIGNED_COMPONENTS


def animation_scalar_factor(field, factor: float) -> float:
    """Keep invariants positive while signed components follow animation polarity."""
    value = float(factor)
    return abs(value) if is_unsigned_component(field) else value


def waveform_factor_extrema(start: float, end: float, function: str) -> tuple[float, ...]:
    """Return exact waveform factors relevant to one clipped playback interval."""
    low = min(max(float(start), 0.0), 1.0)
    high = min(max(float(end), low), 1.0)
    mode = str(function or "Sine").strip().casefold()
    critical = {
        "sine": (0.0, 0.25, 0.5, 0.75, 1.0),
        "half sine": (0.0, 0.5, 1.0),
        "triangle": (0.0, 0.25, 0.5, 0.75, 1.0),
        "ramp": (0.0, 1.0),
    }.get(mode, (0.0, 0.25, 0.5, 0.75, 1.0))
    phases = {low, high}
    phases.update(value for value in critical if low <= value <= high)
    return tuple(current_frame_amplitude(value, function) for value in sorted(phases))


def scaled_animation_range(bounds, field, factors) -> tuple[float, float]:
    """Return the scalar envelope generated by the supplied animation factors."""
    minimum, maximum = (float(value) for value in bounds)
    if minimum > maximum:
        minimum, maximum = maximum, minimum
    values = []
    for factor in tuple(factors or (1.0,)):
        scalar_factor = animation_scalar_factor(field, factor)
        values.extend((minimum * scalar_factor, maximum * scalar_factor))
    return min(values), max(values)


class ResultTimeManagerPanel(TimeManagerPanel):
    """Add result-contour semantics without coupling the base timeline to the ribbon."""

    def __init__(self, results_page=None, viewport=None, parent=None):
        super().__init__(results_page, viewport, parent)
        range_button = getattr(results_page, "range", None)
        signal = getattr(range_button, "animation_envelope_requested", None)
        if signal is not None:
            signal.connect(self._fit_animation_envelope)

    def _render_current_factor(self, factor):
        """Reverse geometry on negative cycles without making invariants negative."""
        if self.viewport is None or self._result is None or self._current_index < 0:
            return
        field = self._frames[self._current_index][2]
        raw_factor = float(factor)
        options = dict(
            self._playback_options or self._animation_options([field])
        )
        if is_unsigned_component(field) and raw_factor < 0.0 and options.get("deform"):
            options["scale"] = -float(options.get("scale", 1.0))
        options["_animation"] = {
            "mode": "factor",
            "source_grid": self._cached_grid(field),
            "factor": animation_scalar_factor(field, raw_factor),
        }
        self.viewport.scene.show_result(self._result, field, options)

    def animation_envelope(self):
        """Return the contour envelope for the active Time Manager playback range."""
        if self._result is None or self._field is None or self.results_page is None:
            return None
        loader = getattr(self.results_page, "loader", None)
        source = str(getattr(self._result, "source_file", "") or "")
        if loader is None or not source:
            return None

        if self.current_frame.isChecked():
            field = (
                self._frames[self._current_index][2]
                if 0 <= self._current_index < len(self._frames)
                else self._field
            )
            try:
                bounds = loader.scalar_range(source, field)
            except (OSError, RuntimeError, TypeError, ValueError):
                return None
            low, high = self._play_ranges["current"]
            factors = waveform_factor_extrema(
                low,
                high,
                self.function_select.currentText(),
            )
            return scaled_animation_range(bounds, field, factors)

        if not self._frames or not self._axis:
            return None
        start, end = self._play_limits()
        start_left, start_right, _ = frame_bracket(self._axis, start)
        end_left, end_right, _ = frame_bracket(self._axis, end)
        first = min(start_left, start_right)
        last = max(end_left, end_right)
        ranges = []
        for index in range(first, last + 1):
            try:
                ranges.append(loader.scalar_range(source, self._frames[index][2]))
            except (OSError, RuntimeError, TypeError, ValueError):
                continue
        if not ranges:
            return None
        return (
            min(value[0] for value in ranges),
            max(value[1] for value in ranges),
        )

    def _fit_animation_envelope(self):
        values = self.animation_envelope()
        range_button = getattr(self.results_page, "range", None)
        if values is not None and range_button is not None:
            range_button.set_range(*values)
